// --- server.js (Final Version with Syntax Fix and Improved AI Output Directives) ---

// 1. Load environment variables from .env file
require('dotenv').config();

// 2. Import necessary libraries
const express = require('express');
const path = require('path');
// Node.js v18+ has a built-in fetch API, so node-fetch is no longer needed

// 3. Initialize Express app and define port
const app = express();
const port = process.env.PORT || 3000;

// 4. Middleware to parse JSON bodies
app.use(express.json());

// 5. Serve static files (assuming your index.html and client-side JS are in the same directory)
app.use(express.static(path.join(__dirname)));

// 6. Get your API keys from the .env file
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY; 
// The HUGGINGFACE_API_KEY is loaded and available for use,
// but the primary setup generation uses OpenRouter as configured below.
const HUGGINGFACE_API_KEY = process.env.HUGGINGFACE_API_KEY;

// --- Validation for API Keys ---
if (!OPENROUTER_API_KEY) {
    console.error("ERROR: OPENROUTER_API_KEY not found in your .env file.");
    console.error("Please ensure you have a .env file in the same directory as server.js");
    console.error("And it contains the line: OPENROUTER_API_KEY=YOUR_ACTUAL_OPENROUTER_KEY_HERE");
    process.exit(1);
}

if (!HUGGINGFACE_API_KEY) {
    // This is a warning because the primary function uses OpenRouter.
    console.warn("WARN: HUGGINGFACE_API_KEY not found in your .env file.");
    console.warn("The application will continue, but features relying on direct Hugging Face calls will fail.");
}

// 7. Define OpenRouter API endpoint and Model
const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const PRIMARY_MODEL = 'NousResearch/Hermes-2-Pro-Llama-3-8B';

// --- Define LMU .VEH Example Templates by Category ---
// IMPORTANT: Each car class has ONE unique, correct, and fully flagged template.
// The [BASIC] section is intentionally ABSENT from these templates as it will be GENERATED by the AI.
const LMU_VEH_TEMPLATES = {
    'Hypercar': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(2,0,0,0)
[GENERAL]
Notes=""
Symmetric=1
CGHeightSetting=0//Non-adjustable (Fixed)
CGRightSetting=0//Non-adjustable (Fixed)
CGRearSetting=0//Non-adjustable (Fixed)
WedgeSetting=0//N/A (Fixed)
FuelSetting=85//85L (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//Max Fuel (Fixed)
VirtualEnergySetting=72//72% (MUST BE OVERWRITTEN)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=88//N/A (Fixed)
Pitstop2Setting=88//N/A (Fixed)
Pitstop3Setting=88//N/A (Fixed)

[LEFTFENDER]
FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
FWSetting=1//Standard (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARWING]
RWSetting=3//P4 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)

[BODYAERO]
WaterRadiatorSetting=1//25% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
OilRadiatorSetting=1//25% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
BrakeDuctSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=16//D-P1 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=0//Detached (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
FrontToeInSetting=15//-0.06 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=17//0.06 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
Front3rdPackerSetting=8//0.8 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Front3rdSpringSetting=8//8 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
Front3rdTenderSpringSetting=0//Detached (Fixed)
Front3rdTenderTravelSetting=0//Detached (Fixed)
Front3rdSlowBumpSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdFastBumpSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdSlowReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdFastReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdPackerSetting=10//1.0 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Rear3rdSpringSetting=7//7 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
Rear3rdTenderSpringSetting=0//Detached (Fixed)
Rear3rdTenderTravelSetting=0//Detached (Fixed)
Rear3rdSlowBumpSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdFastBumpSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdSlowReboundSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdFastReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ChassisAdj00Setting=0//Alternative (Fixed)
ChassisAdj01Setting=0//N/A (Fixed)
ChassisAdj02Setting=0//N/A (Fixed)
ChassisAdj03Setting=0//N/A (Fixed)
ChassisAdj04Setting=0//N/A (Fixed)
ChassisAdj05Setting=0//N/A (Fixed)
ChassisAdj06Setting=0//N/A (Fixed)
ChassisAdj07Setting=0//N/A (Fixed)
ChassisAdj08Setting=0//N/A (Fixed)
ChassisAdj09Setting=0//N/A (Fixed)
ChassisAdj10Setting=0//N/A (Fixed)
ChassisAdj11Setting=0//N/A (Fixed)

[CONTROLS]
SteerLockSetting=0//400 (16) deg (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
RearBrakeSetting=16//52.8:47.2 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
BrakeMigrationSetting=0//2.5% F (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakePressureSetting=80//120 kgf (100%) (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
HandfrontbrakePressSetting=0//0% (Fixed)
HandbrakePressSetting=0//N/A (Fixed)
TCSetting=0//Available (Fixed)
ABSSetting=0//N/A (Fixed)
TractionControlMapSetting=9//9 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCPowerCutMapSetting=8//8 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCSlipAngleMapSetting=8//8 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
AntilockBrakeSystemMapSetting=0//N/A (Fixed)

[ENGINE]
RevLimitSetting=0//8,500 (Non-adjustable) (Fixed)
EngineBoostSetting=0//N/A (Fixed)
RegenerationMapSetting=10//200kW (AI adjusts for session type: Quali=8-9, Race=10) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ElectricMotorMapSetting=3//60kW (AI adjusts for hybrid usage: 0=N/A, 1-4 for power modes) (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
EngineMixtureSetting=1//Race (Min: 0, Max: 2) (MUST BE OVERWRITTEN)
EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=3//2.98:1 (Min: 0, Max: 7) (MUST BE OVERWRITTEN)
ReverseSetting=0//2.07 (6.18) (Fixed)
Gear1Setting=0//2.85 (~62 mph / ~100 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//2.20 (~81 mph / ~130 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//1.82 (~99 mph / ~160 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//1.56 (~118 mph / ~190 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//1.35 (~137 mph / ~220 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//1.19 (~155 mph / ~250 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear7Setting=0//1.05 (~174 mph / ~280 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
RatioSetSetting=0//Short (Min: 0, Max: 1 or higher based on car) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//N/A (Fixed)
DiffPowerSetting=3//25% (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
DiffCoastSetting=10//60% (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
DiffPreloadSetting=24//120 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//N/A (Fixed)
FrontDiffPowerSetting=0//10% (N/A for RWD) (Fixed)
FrontDiffCoastSetting=0//10% (N/A for RWD) (Fixed)
FrontDiffPreloadSetting=0//0 Nm (N/A for RWD) (Fixed)
RearSplitSetting=0// 0.0:100.0 (Fixed to RWD)
GearAutoUpShiftSetting=0//Off (Fixed)
GearAutoDownShiftSetting=0//Off (Fixed)

[FRONTLEFT]
CamberSetting=26//-1.4 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//135 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=5//0.5 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=10//15.95mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=9//4.9 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=26//-1.4 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=5//0.5 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=10//15.95mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=9//4.9 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=15//7.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=15//7.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=6//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[BASIC]
Downforce=0.400000
Balance=0.400000
Ride=0.400000
Gearing=0.400000
Custom=1`,

    'LMP2': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(12,0,0,0)
[GENERAL]
Notes=""
Symmetric=1
//CGHeightSetting=0//Non-adjustable (Fixed)
//CGRightSetting=0//Non-adjustable (Fixed)
//CGRearSetting=0//Non-adjustable (Fixed)
//WedgeSetting=0//N/A (Fixed)
FuelSetting=65//65L (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//N/A (Fixed)
VirtualEnergySetting=72//72% (MUST BE OVERWRITTEN)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=50//N/A (Fixed)
Pitstop2Setting=50//N/A (Fixed)
Pitstop3Setting=50//N/A (Fixed)

[LEFTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
//FWSetting=0//N/A (Fixed)

[REARWING]
RWSetting=2//P3 (Min: 0, Max: 9) (MUST BE OVERWRITTEN)

[BODYAERO]
WaterRadiatorSetting=2//50% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
OilRadiatorSetting=2//50% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
BrakeDuctSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=9//D25 H-H (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=1//D7.5 S-S (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
FrontToeInSetting=13//-0.18 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=22//0.35 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
//RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
Front3rdPackerSetting=6//0.6 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Front3rdSpringSetting=0//N/A (Fixed)
//Front3rdTenderSpringSetting=0//Detached (Fixed)
//Front3rdTenderTravelSetting=0//Detached (Fixed)
//Front3rdSlowBumpSetting=0//1 (Min: 0, Max: 10)
//Front3rdFastBumpSetting=0//1 (Min: 0, Max: 10)
//Front3rdSlowReboundSetting=0//1 (Min: 0, Max: 10)
//Front3rdFastReboundSetting=0//1 (Min: 0, Max: 10)
Rear3rdPackerSetting=7//0.7 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//Rear3rdSpringSetting=0//N/A (Fixed)
//Rear3rdTenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SlowBumpSetting=0//1 (Min: 0, Max: 10)
//FastBumpSetting=0//1 (Min: 0, Max: 10)
//SlowReboundSetting=0//1 (Min: 0, Max: 10)
//FastReboundSetting=0//1 (Min: 0, Max: 10)
//ChassisAdj00Setting=0//N/A (Fixed)

[CONTROLS]
//SteerLockSetting=3//336 (13) deg (Fixed)
RearBrakeSetting=13//54.1:45.9 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
//BrakeMigrationSetting=0// 0.0 (Fixed)
BrakePressureSetting=60//100 kgf (83%) (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
//HandfrontbrakePressSetting=0//0% (Fixed)
//HandbrakePressSetting=0//N/A (Fixed)
//TCSetting=0//Available (Fixed)
//ABSSetting=0//N/A (Fixed)
TractionControlMapSetting=7//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCPowerCutMapSetting=4//4 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCSlipAngleMapSetting=7//Linked (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//AntilockBrakeSystemMapSetting=0//N/A (Fixed)

[ENGINE]
//RevLimitSetting=0//8000 (Fixed)
//EngineBoostSetting=0//N/A (Fixed)
//RegenerationMapSetting=0//0% (Fixed)
ElectricMotorMapSetting=0//Not Applicable (N/A for Non-Hybrid) (Fixed)
EngineMixtureSetting=1//Race (Min: 0, Max: 1) (MUST BE OVERWRITTEN)
//EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=3//2.88:1 (Min: 0, Max: 5) (MUST BE OVERWRITTEN)
ReverseSetting=0//2.85 (8.18) (Fixed)
Gear1Setting=0//2.85 (~56 mph / ~90 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//2.20 (~71 mph / ~115 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//1.88 (~84 mph / ~135 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//1.62 (~96 mph / ~155 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//1.42 (~109 mph / ~175 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//1.27 (~121 mph / ~195 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
RatioSetSetting=1//High Speed (Min: 0, Max: 1 or higher based on car) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//N/A (Fixed)
DiffPowerSetting=0//FF6-60 deg (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
DiffCoastSetting=2//FF6-45 deg (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
DiffPreloadSetting=17//85 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//N/A (Fixed)
FrontDiffPowerSetting=0//0% (Fixed)
FrontDiffCoastSetting=0//0% (Fixed)
FrontDiffPreloadSetting=0//1 (Fixed)
RearSplitSetting=0// 0.0:100.0 (Fixed to RWD)
GearAutoUpShiftSetting=0//Off (Fixed)
GearAutoDownShiftSetting=0//Off (Fixed)

[FRONTLEFT]
CamberSetting=11//-1.5 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=3//0.3 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=5//150N/mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=10//4.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=11//-1.5 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=3//0.3 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=5//150N/mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=10//4.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=24//7.0 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=24//7.0 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[BASIC]
Downforce=0.400000
Balance=0.400000
Ride=0.400000
Gearing=0.400000
Custom=1`,

    'GT3': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(3276,0,0,0)
[GENERAL]
Notes=""
Symmetric=1
//CGHeightSetting=0//Non-adjustable (Fixed)
//CGRightSetting=0//Non-adjustable (Fixed)
//CGRearSetting=0//Non-adjustable (Fixed)
//WedgeSetting=0//N/A (Fixed)
FuelSetting=92//0.93 (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//93.0l (22.5 laps) (Fixed)
VirtualEnergySetting=100//100% (22.0 laps) (Fixed)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=59//N/A (Fixed)
Pitstop2Setting=59//N/A (Fixed)
Pitstop3Setting=59//N/A (Fixed)

[LEFTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
//FWSetting=0//N/A (Fixed)

[REARWING]
RWSetting=2//P3 (Min: 0, Max: 7) (MUST BE OVERWRITTEN)

[BODYAERO]
WaterRadiatorSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
OilRadiatorSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=2//40mm (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=7//P7 (dur) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=4//P4 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FrontToeInSetting=7//-0.117 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=8//0 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
//Front3rdPackerSetting=0//N/A (Fixed)
//Front3rdSpringSetting=0//N/A (Fixed)
//Front3rdTenderSpringSetting=0//Détaché (Fixed)
//Front3rdTenderTravelSetting=0//Détaché (Fixed)
//Front3rdSlowBumpSetting=0//N/A (Fixed)
//Front3rdFastBumpSetting=0//N/A (Fixed)
//Front3rdSlowReboundSetting=0//N/A (Fixed)
//Front3rdFastReboundSetting=0//N/A (Fixed)
//Rear3rdPackerSetting=0//N/A (Fixed)
//Rear3rdSpringSetting=0//N/A (Fixed)
//Rear3rdTenderSpringSetting=0//Détaché (Fixed)
//Rear3rdTenderTravelSetting=0//Détaché (Fixed)
//Rear3rdSlowBumpSetting=0//N/A (Fixed)
//Rear3rdFastBumpSetting=0//N/A (Fixed)
//Rear3rdSlowReboundSetting=0//N/A (Fixed)
//Rear3rdFastReboundSetting=0//N/A (Fixed)

[CONTROLS]
SteerLockSetting=4//380° (11.2°) (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
RearBrakeSetting=21//51.8:48.2 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
//BrakeMigrationSetting=0// 0.0 (Fixed)
//BrakePressureSetting=80//120 kgf (100%) (Fixed)
//HandfrontbrakePressSetting=0//N/A (Fixed)
//HandbrakePressSetting=0//N/A (Fixed)
//TCSetting=0//Disponible (Fixed)
//ABSSetting=0//Disponible (Fixed)
//TractionControlMapSetting=8//8 (Fixed)
TCPowerCutMapSetting=3//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//TCSlipAngleMapSetting=10//10 (Fixed)
AntilockBrakeSystemMapSetting=11//11 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)

[ENGINE]
//RevLimitSetting=0//9,400 (Fixed)
//EngineBoostSetting=0//N/A (Fixed)
//RegenerationMapSetting=0//0% (Fixed)
ElectricMotorMapSetting=0//Not Applicable (N/A for Non-Hybrid) (Fixed)
//EngineMixtureSetting=1//Race (Fixed)
//EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=0//Fixed (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ReverseSetting=0//Fixed
Gear1Setting=0//Fixed (~95 km/h / ~59 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//Fixed (~130 km/h / ~81 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//Fixed (~160 km/h / ~99 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//Fixed (~190 km/h / ~118 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//Fixed (~220 km/h / ~137 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//Fixed (~250 km/h / ~155 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
RatioSetSetting=0//Short (Min: 0, Max: 1) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//Non-adjustable (Fixed)
DiffPowerSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
DiffCoastSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
DiffPreloadSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//0% (Fixed)
FrontDiffPowerSetting=0//0% (Fixed)
FrontDiffCoastSetting=0//0% (Fixed)
FrontDiffPreloadSetting=0//1 (Fixed)
RearSplitSetting=0//RWD (Fixed)
GearAutoUpShiftSetting=0//Non (Fixed)
GearAutoDownShiftSetting=0//Non (Fixed)

[FRONTLEFT]
CamberSetting=26//-1.80 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=9//0.9 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=3//4 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Standard (Fixed)
//SpringRubberSetting=0//N/A (Fixed)
//RideHeightSetting=0//5.0 cm (MUST BE OVERWRITTEN)
SlowBumpSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//12 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.56 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=26//-1.80 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=9//0.9 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=3//4 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Standard (Fixed)
//SpringRubberSetting=0//N/A (Fixed)
//RideHeightSetting=0//5.0 cm (MUST BE OVERWRITTEN)
SlowBumpSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//12 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.56 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=25//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=14//1.4 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=1//2 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=16//6.6 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=7//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=25//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=14//1.4 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=1//2 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=16//6.6 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=7//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[BASIC]
Downforce=0.400000
Balance=0.400000
Ride=0.400000
Gearing=0.400000
Custom=1`
};

// 8. Define a route for AI setup requests
app.post('/generate-setup', async (req, res) => {
    // Safely destructure all possible values from the request body
    const {
        car, track, request, selectedCarCategory,
        selectedCarDisplay, selectedTrackDisplay, setupGoal,
        sessionGoal, selectedWeather, trackTemp, specificRequest, driverFeedback
    } = req.body;

    // Validate essential parameters
    if (!car || !track || !setupGoal || !selectedCarCategory) {
        return res.status(400).json({
            error: "Please provide Car, Track, Setup Goal, and Car Category details."
        });
    }

    // Handle potential category key mismatch
    let finalCategory = selectedCarCategory;
    if (selectedCarCategory === 'LMGT3' && LMU_VEH_TEMPLATES['GT3']) {
        finalCategory = 'GT3';
    } else if (selectedCarCategory === 'GT3' && LMU_VEH_TEMPLATES['LMGT3']) {
        finalCategory = 'LMGT3';
    }

    let exampleTemplate = LMU_VEH_TEMPLATES[finalCategory];
    if (!exampleTemplate) {
        return res.status(400).json({
            error: `No .VEH template found for car category: ${finalCategory}. Ensure selected car has a valid category.`
        });
    }

    // --- CRITICAL: LE MANS SPECIFIC OVERRIDE LOGIC (Server-Side Enforcement) ---
    // This ensures Le Mans gets the absolute lowest drag settings regardless of AI's broader interpretation.
    let finalExampleTemplate = exampleTemplate; // Start with the chosen template

    if (track === "Circuit de la Sarthe (Le Mans)") {
        const minRwSetting = 0; // Absolute minimum RW for all classes on Le Mans

        // Programmatically replace RWSetting to its absolute minimum for Le Mans
        finalExampleTemplate = finalExampleTemplate.replace(/^(RWSetting=)\d+/m, `$1${minRwSetting}`);

        // Programmatically replace FinalDriveSetting to its highest for Le Mans
        let leMansFinalDrive;
        if (finalCategory === 'Hypercar') {
            leMansFinalDrive = 7; 
        } else if (finalCategory === 'LMP2') {
            leMansFinalDrive = 5; 
        } else if (finalCategory === 'GT3' || finalCategory === 'GTE') {
            leMansFinalDrive = 10; // Assuming 10 is max for GT3/GTE fixed gears
        }
        finalExampleTemplate = finalExampleTemplate.replace(/^(FinalDriveSetting=)\d+\s*\/\/.*/m, `$1${leMansFinalDrive}`);
        
        // Programmatically force ALL individual gears to 1 (Longest Ratio)
        finalExampleTemplate = finalExampleTemplate.replace(/^(Gear\dSetting=)\d+/gm, `$11`);

        // Inject a specific note into the template about the Le Mans override, so the AI knows
        // this was pre-set and should still explain it in its notes.
        finalExampleTemplate = finalExampleTemplate.replace(/Notes=""/, `Notes="Le Mans override applied: Absolute minimum drag prioritized. RWSetting set to ${minRwSetting}. [BASIC].Downforce will be extremely low. All individual gears set to Longest. FinalDrive set to ${leMansFinalDrive}. This overrides general setup goals for max top speed."`);
    }

    // UPGRADE: Dynamically insert the user's selected car name into the template
    finalExampleTemplate = finalExampleTemplate.replace('[[CAR_NAME]]', car);


    const sessionDuration = req.body.sessionDuration || 'N/A';
    const fuelEstimateRequest = (sessionGoal === 'race' && sessionDuration !== 'N/A' && !isNaN(parseInt(sessionDuration))) ?
        `Estimate fuel for a ${sessionDuration} minute race.` : '';
    const weatherGuidance = `Current weather is ${selectedWeather}.`;
    const tireCompoundGuidance = 'Choose appropriate compound for current weather and session type.';


    // =====================================================================================
    // --- AI PROMPT --- THIS IS THE CRITICAL SECTION THAT HAS BEEN IMPROVED ---
    // =====================================================================================
    const prompt = `
## PRIME DIRECTIVE
Generate a complete, physically realistic, and numerically valid .VEH setup. Replace placeholders with calculated, logical numbers. '0' for adjustable settings is a failure.

## PERSONA & PHILOSOPHY
World-class LMU race engineer. Goal: predictable, realistic setups, suited to driver/feedback. Explain decisions in 'Notes'.

## CRITICAL INSTRUCTION
Populate '[GENERAL] Notes' with engineering debrief. If track-specific override (e.g., Le Mans aero) applied, explicitly state it, explaining how it overrides general setup philosophies. For key adjustments, explain the engineering reason.

## THOUGHT PROCESS & HIERARCHY
1.  **Session Type (Qualifying vs. Race):** Dictates setup philosophy.
2.  **Driver Feedback is KING:** Address 'Driver Problem to Solve' first. Consult 'DRIVER FEEDBACK TROUBLESHOOTING MATRIX'. Apply Primary/Secondary solutions. All other decisions align.
3.  **Track DNA & Weather:** Analyze track demands ('TRACK DNA DATABASE') and weather ('ADVANCED WEATHER & TIRE STRATEGY'). Apply baseline decisions. Mention track compromise in notes.
4.  **Car Architecture:** Apply adjustments based on car's traits ('CAR ARCHITECTURE PHILOSOPHY').
5.  **Overall Setup Goal:** Use 'Setup Goal' ('Safe', 'Balanced', 'Aggressive') from 'LMU SETUP PHILOSOPHY DIAL' to fine-tune settings.
5.5. **Generate [BASIC] Parameters (MANDATORY):** Dynamically calculate and GENERATE the [BASIC] section at .VEH end. This is NOT in template. Fully derived.
    - Every parameter ('Downforce', 'Balance', 'Ride', 'Gearing') MUST be a uniquely calculated float (e.g., 0.125000).
    - Outputting 0.500000 (or any common default) is critical failure, UNLESS your calculation is optimal.
    - **'Downforce'**: Low-drag (0.075-0.25). High-downforce/grip (0.75-0.925). Mid for balanced (0.35-0.65).
    - **'Balance'**: Aggressive oversteer (0.15-0.35). Neutral (0.45-0.55). Stable understeer (0.65-0.85). Per driver/track.
    - **'Ride'**: Stiff/low (0.075-0.25). Compliant/high (0.75-0.925). Mid (0.35-0.65). Per track bumps.
    - **'Gearing'**: Long/top speed (0.85-0.975). Short/acceleration (0.075-0.25). Mid (0.25-0.85). MUST correspond to detailed gear selections.
    - **Custom**: 1.
6.  **Engineer's Debrief:** Write concise summary in 'Notes'.

## LMU GAME MECHANICS & NUANCES
- Tuning MUST be LMU simulation-based.

### LMU Gearing Index Behavior
- Individual gears ('Gear1Setting' to 'Gear7Setting'): **INVERSE relationship**.
    - LOWER index (0) = SHORTEST ratio.
    - HIGHER index (1) = LONGEST ratio.
- **Range Limit**: Individual gears LIMITED TO ONLY INDICES 0 AND 1.
- 'FinalDriveSetting': HIGHER index = longer overall gearing.
- Apply LMU-specific gearing logic.

### Other Nuances
- 'FuelSetting', 'VirtualEnergySetting', 'NumPitstopsSetting' adjust.
- UpgradeSetting values fixed.

## LMU PHYSICS & TUNING REFERENCE
- **Aero**: Wings ('FWSetting'/'RWSetting'): Grip vs. drag. Ducts: temp/drag.
- **Suspension**: Springs ('PackerSetting'/'SpringSetting') control ride height/stiffness. Dampers ('Slow Bump'/'Fast Bump', 'Slow Rebound'/'Fast Rebound') control movement. 'AntiSwaySetting' (ARB) controls body roll/load. 'CamberSetting' controls tire angle. 'ToeInSetting' controls tire angle. 'RideHeightSetting' impacts drag/CG. Packers limit travel.
- **Drivetrain**: 'FinalDriveSetting' overall gear ratio. Individual gears fine-tune. Differential ('DiffPowerSetting', 'DiffCoastSetting', 'DiffPreloadSetting') controls power.
- **Brakes**: 'RearBrakeSetting' (Bias), 'BrakePressureSetting', 'AntilockBrakeSystemMapSetting' (ABS), 'TractionControlMapSetting' (TC).

## LMU TUNING GUIDELINES & RANGES
- Prioritize realistic values.

### Tires
- 'PressureSetting': (Min: 0/~130 kPa, Max: 10/~170 kPa).
- 'CompoundSetting': **LMU specific compound availability:**
    - Hypercar/GTE: 0=Wet, 1=Soft, 2=Medium, 3=Hard.
    - LMP2/GT3: ONLY 0=Wet, 1=Medium. (Soft/Hard NOT available).
    - MUST select available compound.

### Aero
- 'FWSetting'/'RWSetting' indices: (0=low, higher=more downforce). Max: Hypercar FW:2, RW:10; LMP2 RW:9; GT3 RW:7; GTE RW:10.
- BrakeDucts indices: (0=open/max cooling, higher=more closed/less cooling/more aero). Max: Hypercar:3, GT3:3, GTE:3.
- **Dynamic Radiator/Brake Duct**: Adjust 'BrakeDuctSetting'/'WaterRadiatorSetting'/'OilRadiatorSetting' based on 'Track Temp'. High temp = more open (higher index). Low temp = more closed (lower index).

### Suspension
- 'RideHeightSetting': (Min: 0/~4.0 cm, Max: 30/~8.0 cm).
- 'SpringSetting': (Min: 0, Max: 20).
- 'AntiSwaySetting (ARB)': (Min: 0, Max: 20).
- 'Camber Setting': (Min: 0/~-0.5 deg, Max: 40/~-4.0 deg).
- 'Toe In/Out': ('FrontToeInSetting'/'RearToeInSetting') (Min: 0/~-0.2 deg, Max: 30/~+0.2 deg).
- Damper Settings: ('Slow Bump'/'Fast Bump'/'Slow Rebound'/'Fast Rebound') (Min: 0, Max: 10). Soft=0-3, Medium=4-7, Stiff=8-10. Bumpy tracks need softer Fast.
- **Suspension Philosophy**: Springs, packers, dampers must ensure effective vertical load management and maximum tire contact.

### Drivetrain
- 'FinalDriveSetting': (Min: 0, Max: typically 5-10).
- 'Individual Gear Settings': ('Gear1Setting'-'Gear7Setting') (Min: 0, Max: 1).
- 'DiffPowerSetting': (Min: 0, Max: 15).
- 'DiffCoastSetting': (Min: 0, Max: 20).
- 'DiffPreloadSetting': (Min: 0, Max: 100).
- 'RatioSetSetting': (Min: 0, Max: 1).

### Brakes
- 'RearBrakeSetting' (Bias): (Min: 0, Max: 40).
- 'BrakePressureSetting': (Min: 0, Max: 100).
- 'AntilockBrakeSystemMapSetting' (ABS): (Min: 0, Max: 15).
- 'TractionControlMapSetting' (TC): (Min: 0, Max: 10).

## GEARING STRATEGY (CRITICAL)
1.  **High-Speed Tracks (e.g., Le Mans, Monza):**
    - 'FinalDriveSetting': MUST be HIGHEST available index.
    - 'Gear1Setting' to 'GearXSetting': MUST all be **1 (Longest)**.
    - Comments: MUST include realistic approx speed (~Y mph / ~Z km/h).
    - Self-Verification: Confirm 6th/7th gear top speed >300 km/h (>185 mph) for Hypercars/LMP2s.
2.  **Technical/Accelerative Tracks (e.g., Sebring, Portimão):**
    - 'FinalDriveSetting': MUST be LOWER available index.
    - 'Gear1Setting' to 'GearXSetting': MUST all be **0 (Shortest)**.
    - Comments: MUST include realistic approx speed (~Y mph / ~Z km/h).
ALWAYS ensure non-zero index for adjustable gears (not fixed 0).

## TRACK DNA DATABASE
- **Circuit de la Sarthe (Le Mans):** High-speed. Focus: LOWEST drag (low wings, VERY LONG GEARS). The **'Downforce'** parameter in [BASIC] **MUST be set to its ABSOLUTE LOWEST possible value (e.g., 0.050000 - 0.080000)**. Any higher is critical failure. The **'REARWING (RWSetting)'** MUST be its **absolute minimum index (e.g., 0 or 1)**. Individual gear ratios ('Gear1Setting' to 'GearXSetting') MUST all be **1 (Longest Ratio)**. This ensures lowest drag/max top speed, overriding other general setup goals. Compromise: stability for Porsche Curves. Bumps need good high-speed damping.
- **Sebring International Raceway:** Extremely bumpy. Focus: SOFT suspension (especially fast dampers), higher ride height. Compromise: softness can hurt responsiveness. Short Gears Recommended.
- **Spa-Francorchamps:** High-speed, elevation change. Focus: High-speed stability, good aero balance. Stiff springs for Eau Rouge. Long Gears Recommended.
- **Autodromo Nazionale Monza:** Very high-speed. Focus: LOWEST drag, even more than Le Mans. **VERY LONG GEARS ESSENTIAL**. Compromise: stable braking.
- **Fuji Speedway:** Long main straight, technical final sector. Focus: Compromise top speed/low-speed agility. Balanced Gearing Recommended.
- **Autódromo Internacional do Algarve (Portimão):** "Rollercoaster", elevation, blind crests. Focus: Predictable, stable platform. Medium downforce, compliant suspension. Slightly Shorter Gears Recommended.
- **Bahrain International Circuit:** High grip, smooth, hot. Focus: Good braking stability, traction. Tire wear high. Balanced Gearing Recommended.

## LMU SETUP PHILOSOPHY DIAL (PACE & DRIVEABILITY)
- **'Aggressive' Setup Goal:** Maximize driveable peak performance/responsiveness. NEVER compromise to undrivable/unstable car. Sharp, reactive, consistently fast. Aero lower for speed, mechanical grip for rotation.
- **'Balanced' Setup Goal:** Optimize versatile, all-around performance. Strong compromise stability/responsiveness. Predictable, efficient. Aero/mechanical harmonized for neutral feel.
- **'Safe' Setup Goal:** Maximize driver confidence/stability (error reduction) while maintaining strong, consistent pace. Forgiving, not sluggish/losing significant time. Aero higher for stability, suspension softer.

## QUALIFYING VS. RACE PHILOSOPHY
- **'qualifying'**: One-lap pace, optimal timing. Softest tires, minimal fuel (2-3 laps), aggressive camber, high brake pressure, aggressive diff. Tire wear irrelevant.
- **'race'**: Consistent pace/lap times over stint, NOT just tire survival. Efficient, predictable car maintaining speed through degradation. Optimized tire pressures for consistency. Balance pace & tire wear when choosing 'PressureSetting'/'CamberSetting'.

## CAR ARCHITECTURE PHILOSOPHY
- **Mid-Engine (Prototypes, Ferrari, Vanwall, Peugeot):** Balanced, flexible.
- **Rear-Engine (Porsche 911 RSR / GT3 R):** Excellent traction, prone entry understeer. Benefit aggressive front-end (soft front ARB, more negative front camber).
- **Front-Engine (Corvette, Aston Martin):** Stable braking, prone entry understeer. Benefit rear-end rotation (stiffer rear ARB, aggressive diff).
- **General Principle:** Lean into positive car characteristics; mitigate negative ones.

## DRIVER FEEDBACK TROUBLESHOOTING MATRIX (High Priority)
- IF "Understeer on corner entry": 1st: Reduce 'DiffCoastSetting'. 2nd: Soften 'FrontAntiSwaySetting'. 3rd: Increase 'FrontToeInSetting'.
- IF "Understeer mid-corner or on exit": 1st: Stiffen 'RearAntiSwaySetting'. 2nd: Reduce 'DiffPowerSetting'. 3rd: Increase 'FrontCamberSetting'.
- IF "Oversteer on corner entry" or "nervous": 1st: Increase 'DiffCoastSetting'. 2nd: Stiffen 'FrontAntiSwaySetting'. 3rd: Decrease 'RearToeInSetting'.
- IF "Oversteer on exit" or "Poor traction" / "Loose rear": 1st: INCREASE 'RearCamberSetting' (less negative - HIGHER index) for stability. 2nd: Increase 'RearToeInSetting' (more toe-in) for stability. 3rd: Soften 'RearAntiSwaySetting'. 4th: Increase 'DiffPowerSetting' (on-throttle lock). 5th: Increase 'DiffCoastSetting' (off-throttle lock).
- IF "Unstable under braking": 1st: Decrease 'RearBrakeSetting'. 2nd: Increase 'EngineBrakingMapSetting'. 3rd: Increase 'DiffCoastSetting'.
- IF "Too much Understeer" or "Pushing in corners": 1st: DECREASE 'RearCamberSetting' (more negative - LOWER index) for more rotation. 2nd: Decrease 'RearToeInSetting' (less toe-in). 3rd: Stiffen 'RearAntiSwaySetting'.

## ADVANCED WEATHER & TIRE STRATEGY
- IF Weather is 'Rain'/'Wet': Wet tires ('CompoundSetting'=0), INCREASE 'PressureSetting' (+3-5 clicks), INCREASE 'RideHeightSetting' (+10-15 cm), SOFTER Springs/Dampers, HIGHER TC/ABS. Open BrakeDucts.
- IF Track Temp high (>30C): Lower tire pressures/harder compounds (overheating). Open brake ducts slightly.
- IF Track Temp low (<15C): Higher tire pressures/softer compounds (build temp). Close brake ducts slightly.

## SETUP SANITY CHECKS
1.  Low RideHeight REQUIRES Stiff Springs.
2.  High Aero ('RWSetting') REQUIRES Stiff Springs.
3.  Bumpy Tracks REQUIRE Softer Fast Damping.
4.  **Gearing Sanity Check:** High-Speed Tracks: 'FinalDriveSetting' HIGH, 'GearXSetting' 1 (Longest). Technical Tracks: 'FinalDriveSetting' LOW, 'GearXSetting' 0 (Shortest).
5.  Physics Check: Realistic toe/camber.
6.  Physics: Dampers complement springs/track.
7.  Balance Consistency: Aero, mechanical, diff in harmony.
8.  'FinalDrive' & Gears Cohesion: Logical progression, appropriate top speeds.
9.  Fuel Consistency: Fuel load aligns with session/track.
10. Tire Compound Logic: 'CompoundSetting' aligns with weather/session.

## COMMON SETUP COMPROMISES
- More Downforce = Less Top Speed.
- Stiffer Suspension = More Responsive, Less Compliant.
- Softer Suspension = More Compliant, Less Responsive.
- Long Gearing = High Top Speed, Slower Acceleration.
- Short Gearing = Quick Acceleration, Lower Top Speed.
- Aggressive Camber = More Cornering Grip, Less Straight-line Stability/Braking.
- High Brake Pressure = More Stopping Power, Higher Risk of Lockup.
- Forward Brake Bias = More Stable Braking, Risk of Front Lockup.
- Rearward Brake Bias = More Rotation/Turn-in on Braking, Risk of Rear Lockup/Spin.
- High Differential Lock = More Traction/Stability, More Understeer (Power) / Snap Oversteer (Coast).

## DRIVER CONFIDENCE & CONSISTENCY PRINCIPLES
- Predictability over Peak Aggression.
- Stability under Braking & Power.
- Smooth Transitions.
- Tire Preservation (Race Sessions) for pace.
- Forgiveness.
- Neutral Balance (or predictable understeer).

## LMU AI GUIDANCE REFINEMENTS (ULTIMATE PRECISION)
- **NO STATIC DEFAULTS:** MUST NOT output values identical to template defaults unless optimal. Defaulting is critical failure.
- **INTERCONNECTEDNESS:** All parameters interdependent.
- **LMU REALISM CHECK:** Ensure physically realistic/plausible settings.
- **DYNAMIC RANGE UTILIZATION:** Actively use full Min-Max range.
- **OPTIMAL RIDE QUALITY:** Prioritize optimal tire contact.
- **SPECIFIC NUMERICAL DEVIATION:** Use distinct floats for [BASIC]/Camber.

## FINAL REQUEST DETAILS
Car: ${car} (Display Name: ${selectedCarDisplay}, Category: ${finalCategory})
Track: ${track} (Display Name: ${selectedTrackDisplay})
Setup Goal: ${setupGoal}
Driver Problem to Solve: ${driverFeedback}
Session Goal: ${sessionGoal}
Session Duration: ${sessionDuration} minutes
Weather: ${selectedWeather} (${weatherGuidance})
Track Temperature: ${trackTemp}°C
Specific User Request: ${specificRequest}
${fuelEstimateRequest}
${tireCompoundGuidance}

This is the required LMU .VEH structure. You MUST use this exact structure, replacing all placeholder values with valid integers and dynamically calculated comments. Your response MUST begin IMMEDIATELY with 'VehicleClassSetting=' and contain ONLY the file content. No extra text, no markdown code block formatting, no introductory or concluding remarks whatsoever.
${finalExampleTemplate}

Now, generate the complete and valid .VEH file. Your response MUST contain ONLY the file content and nothing else.
`; 

    try {
        const openrouterResponse = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': 'Bearer ' + OPENROUTER_API_KEY, 
                'Content-Type': 'application/json',
                'X-Title': 'LMU Setup Generator',
            },
            body: JSON.stringify({
                model: PRIMARY_MODEL,
                messages: [{
                    role: "user",
                    content: prompt
                }],
                max_tokens: 8192, 
                temperature: 0.8, 
            }),
        });

        if (!openrouterResponse.ok) {
            const errorData = await openrouterResponse.json();
            console.error("Error from OpenRouter API:", openrouterResponse.status, errorData);
            return res.status(openrouterResponse.status).json({
                error: `OpenRouter API Error: ${errorData.error ? errorData.error.message : 'Unknown API error'} (Status: ${openrouterResponse.status})`
            });
        }

        const chatCompletion = await openrouterResponse.json();
        const rawText = chatCompletion.choices[0].message.content;

        // --- NEW ROBUST PARSING LOGIC ---
        // Find the start of the actual .VEH content. The AI sometimes adds introductory text.
        const setupStartIndex = rawText.indexOf('VehicleClassSetting=');

        if (setupStartIndex !== -1) {
            // If the start string is found, extract everything from that point on.
            let setupText = rawText.substring(setupStartIndex);

            // Also remove any trailing markdown code blocks if they exist
            if (setupText.trim().endsWith('```')) {
                setupText = setupText.trim().slice(0, -3).trim();
            }

            // Log the generated setup to the console for debugging
            console.log("\n--- GENERATED SETUP ---\n", setupText);

            res.json({
                setup: setupText
            });

        } else {
            // If 'VehicleClassSetting=' is not found at all, the response is invalid.
            console.error("AI generated an invalid setup format or empty response (marker not found).");
            console.error("AI Raw Response (first 500 chars):", rawText ? rawText.substring(0, 500) : '[Empty Response]'); // Log a snippet
            res.status(500).json({
                error: `AI generated an invalid setup format. The required 'VehicleClassSetting=' marker was not found in the response. Please try again. Raw AI response snippet: ${rawText ? rawText.substring(0, 200) : '[Empty Response]'}`
            });
        }

    } catch (error) {
        console.error("Error communicating with OpenRouter or generating setup:", error);
        res.status(500).json({
            error: `Failed to connect to OpenRouter. Check VS Code terminal. Error: ${error.message}`
        });
    }
});

// 9. Start the server
app.listen(port, () => {
    console.log(`Server is running at http://localhost:${port}`);
    console.log(`Open your web browser and navigate to http://localhost:${port}`);
    console.log("Keep this terminal window open while using the generator.");
});
