// --- server.js (Final Version with Masterized AI Knowledge Base) ---

// 1. Load environment variables from .env file
require('dotenv').config();

// 2. Import necessary libraries
const express = require('express');
const path = require('path');
// Node.js v18+ has a built-in fetch API, so node-fetch is no longer needed

// 3. Initialize Express app and define port
const app = express();
const port = process.env.PORT || 3000;

// 4. Middleware to parse JSON bodies
app.use(express.json());

// 5. Serve static files (assuming your index.html and client-side JS are in the same directory)
app.use(express.static(path.join(__dirname)));

// 6. Get your API keys from the .env file
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
// The HUGGINGFACE_API_KEY is loaded and available for use,
// but the primary setup generation uses OpenRouter as configured below.
const HUGGINGFACE_API_KEY = process.env.HUGGINGFACE_API_KEY;

// --- Validation for API Keys ---
if (!OPENROUTER_API_KEY) {
    console.error("ERROR: OPENROUTER_API_KEY not found in your .env file.");
    console.error("Please ensure you have a .env file in the same directory as server.js");
    console.error("And it contains the line: OPENROUTER_API_KEY=YOUR_ACTUAL_OPENROUTER_KEY_HERE");
    process.exit(1);
}

if (!HUGGINGFACE_API_KEY) {
    // This is a warning because the primary function uses OpenRouter.
    console.warn("WARN: HUGGINGFACE_API_KEY not found in your .env file.");
    console.warn("The application will continue, but features relying on direct Hugging Face calls will fail.");
}

// 7. Define OpenRouter API endpoint and Model
const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const PRIMARY_MODEL = 'NousResearch/Hermes-2-Pro-Llama-3-8B';

// --- Define LMU .VEH Example Templates by Category (ENHANCED with safer defaults) ---
// IMPORTANT: Each car class has ONE unique, correct, and fully flagged template.
// The [BASIC] section is INTENTIONALLY ABSENT from these templates as it will be GENERATED by the AI.
const LMU_VEH_TEMPLATES = {
    'Hypercar': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(2,0,0,0) // Fixed to car's upgrade package
[GENERAL]
Notes=""
Symmetric=1
//CGHeightSetting=0//Non-adjustable (Fixed)
//CGRightSetting=0//Non-adjustable (Fixed)
//CGRearSetting=0//Non-adjustable (Fixed)
//WedgeSetting=0//N/A (Fixed)
FuelSetting=85//85L (MUST BE OVERWRITTEN)
//FuelCapacitySetting=0//Max Fuel (Fixed)
VirtualEnergySetting=72//72% (MUST BE OVERWRITTEN)
//NumPitstopsSetting=0//N/A (Fixed)
//Pitstop1Setting=88//N/A (Fixed)
//Pitstop2Setting=88//N/A (Fixed)
//Pitstop3Setting=88//N/A (Fixed)

[LEFTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
FWSetting=1//Standard (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARWING]
RWSetting=3//P4 (Min: 0, Max: 11) (MUST BE OVERWRITTEN) // Hypercar RW: 0-11 (P1-P12 in game UI)

[BODYAERO]
WaterRadiatorSetting=1//25% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
OilRadiatorSetting=1//25% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
BrakeDuctSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=16//D-P1 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=10//Balanced Default (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
FrontToeInSetting=15//-0.06 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=17//0.06 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
Front3rdPackerSetting=8//0.8 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Front3rdSpringSetting=8//8 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
Front3rdTenderSpringSetting=0//Detached (Fixed)
Front3rdTenderTravelSetting=0//Detached (Fixed)
Front3rdSlowBumpSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdFastBumpSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdSlowReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdFastReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdPackerSetting=10//1.0 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Rear3rdSpringSetting=7//7 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
Rear3rdTenderSpringSetting=0//Detached (Fixed)
Rear3rdTenderTravelSetting=0//Detached (Fixed)
Rear3rdSlowBumpSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdFastBumpSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdSlowReboundSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdFastReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ChassisAdj00Setting=0//Alternative (Fixed)
ChassisAdj01Setting=0//N/A (Fixed)
ChassisAdj02Setting=0//N/A (Fixed)
ChassisAdj03Setting=0//N/A (Fixed)
ChassisAdj04Setting=0//N/A (Fixed)
ChassisAdj05Setting=0//N/A (Fixed)
ChassisAdj06Setting=0//N/A (Fixed)
ChassisAdj07Setting=0//N/A (Fixed)
ChassisAdj08Setting=0//N/A (Fixed)
ChassisAdj09Setting=0//N/A (Fixed)
ChassisAdj10Setting=0//N/A (Fixed)
ChassisAdj11Setting=0//N/A (Fixed)

[CONTROLS]
SteerLockSetting=0//400 (16) deg (MUST BE OVERWRITTEN)
RearBrakeSetting=16//52.8:47.2 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
BrakeMigrationSetting=0//2.5% F (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakePressureSetting=80//120 kgf (100%) (MUST BE OVERWRITTEN)
//HandfrontbrakePressSetting=0//0% (Fixed)
//HandbrakePressSetting=0//N/A (Fixed)
//TCSetting=0//Available (Fixed)
//ABSSetting=0//N/A (Fixed)
TractionControlMapSetting=9//9 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCPowerCutMapSetting=8//8 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCSlipAngleMapSetting=8//8 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//AntilockBrakeSystemMapSetting=0//N/A (Fixed)

[ENGINE]
//RevLimitSetting=0//8,500 (Non-adjustable) (Fixed)
//EngineBoostSetting=0//N/A (Fixed)
RegenerationMapSetting=10//200kW (AI adjusts for session type: Quali=8-9, Race=10) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ElectricMotorMapSetting=3//60kW (AI adjusts for hybrid usage: 0=N/A, 1-4 for power modes) (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
EngineMixtureSetting=1//Race (Min: 0, Max: 2) (MUST BE OVERWRITTEN)
//EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
//FinalDriveSetting=0//2.98:1 (Fixed)
//ReverseSetting=0//2.07 (6.18) (Fixed)
Gear1Setting=0//2.85 (~62 mph / ~100 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//2.20 (~81 mph / ~130 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//1.82 (~99 mph / ~160 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//1.56 (~118 mph / ~190 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//1.35 (~137 mph / ~220 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//1.19 (~155 mph / ~250 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Longest ratio.
Gear7Setting=0//1.05 (~174 mph / ~280 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
RatioSetSetting=0//Short (Min: 0, Max: 1 or higher based on car) (MUST BE OVERWRITTEN)
//DiffPumpSetting=0//N/A (Fixed)
DiffPowerSetting=3//25% (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
DiffCoastSetting=10//60% (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
DiffPreloadSetting=24//120 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//N/A (Fixed)
FrontDiffPowerSetting=0//10% (N/A for RWD) (Fixed)
FrontDiffCoastSetting=0//10% (N/A for RWD) (Fixed)
FrontDiffPreloadSetting=0//0 Nm (N/A for RWD) (Fixed)
RearSplitSetting=0// 0.0:100.0 (Fixed to RWD)
GearAutoUpShiftSetting=0//Off (Fixed)
GearAutoDownShiftSetting=0//Off (Fixed)

[FRONTLEFT]
CamberSetting=26//-1.4 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//135 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=5//0.5 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=10//15.95mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=9//4.9 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//4.00 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=26//-1.4 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=5//0.5 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=10//15.95mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=9//4.9 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=15//7.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=15//7.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=6//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//4.00 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)`,

    'LMP2': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(12,0,0,0) // Fixed to car's upgrade package
[GENERAL]
Notes=""
Symmetric=1
CGHeightSetting=0//Non-adjustable (Fixed)
CGRightSetting=0//Non-adjustable (Fixed)
CGRearSetting=0//Non-adjustable (Fixed)
WedgeSetting=0//N/A (Fixed)
FuelSetting=65//65L (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//N/A (Fixed)
VirtualEnergySetting=72//72% (MUST BE OVERWRITTEN)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=50//N/A (Fixed)
Pitstop2Setting=50//N/A (Fixed)
Pitstop3Setting=50//N/A (Fixed)

[LEFTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
//FWSetting=0//N/A (Fixed)

[REARWING]
RWSetting=2//P3 (Min: 0, Max: 8) (MUST BE OVERWRITTEN) // LMP2 RW: 0-8 (P1-P9 in game UI)

[BODYAERO]
WaterRadiatorSetting=2//50% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
OilRadiatorSetting=2//50% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
BrakeDuctSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=9//D25 H-H (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=5//Balanced Default (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
FrontToeInSetting=13//-0.18 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=22//0.35 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
//RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
Front3rdPackerSetting=6//0.6 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Front3rdSpringSetting=0//N/A (Fixed)
//Front3rdTenderSpringSetting=0//Detached (Fixed)
//Front3rdTenderTravelSetting=0//Detached (Fixed)
//Front3rdSlowBumpSetting=0//1 (Min: 0, Max: 10)
//Front3rdFastBumpSetting=0//1 (Min: 0, Max: 10)
//Front3rdSlowReboundSetting=0//1 (Min: 0, Max: 10)
//Front3rdFastReboundSetting=0//1 (Min: 0, Max: 10)
Rear3rdPackerSetting=7//0.7 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//Rear3rdSpringSetting=0//N/A (Fixed)
//Rear3rdTenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SlowBumpSetting=0//1 (Min: 0, Max: 10)
//FastBumpSetting=0//1 (Min: 0, Max: 10)
//SlowReboundSetting=0//1 (Min: 0, Max: 10)
//FastReboundSetting=0//1 (Min: 0, Max: 10)
//ChassisAdj00Setting=0//N/A (Fixed)

[CONTROLS]
//SteerLockSetting=3//336 (13) deg (Fixed)
RearBrakeSetting=13//54.1:45.9 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
//BrakeMigrationSetting=0// 0.0 (Fixed)
BrakePressureSetting=60//100 kgf (83%) (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
//HandfrontbrakePressSetting=0//0% (Fixed)
//HandbrakePressSetting=0//N/A (Fixed)
//TCSetting=0//Available (Fixed)
//ABSSetting=0//N/A (Fixed)
TractionControlMapSetting=7//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCPowerCutMapSetting=4//4 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCSlipAngleMapSetting=7//Linked (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//AntilockBrakeSystemMapSetting=0//N/A (Fixed)

[ENGINE]
//RevLimitSetting=0//8000 (Fixed)
//EngineBoostSetting=0//N/A (Fixed)
//RegenerationMapSetting=0//0% (Fixed)
ElectricMotorMapSetting=0//Not Applicable (N/A for Non-Hybrid) (Fixed)
EngineMixtureSetting=1//Race (Min: 0, Max: 1) (MUST BE OVERWRITTEN)
//EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=3//2.88:1 (Min: 0, Max: 5) (MUST BE OVERWRITTEN)
ReverseSetting=0//2.85 (8.18) (Fixed)
Gear1Setting=0//2.85 (~56 mph / ~90 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//2.20 (~71 mph / ~115 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//1.88 (~84 mph / ~135 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//1.62 (~96 mph / ~155 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//1.42 (~109 mph / ~175 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//1.27 (~121 mph / ~195 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
RatioSetSetting=1//High Speed (Min: 0, Max: 1 or higher based on car) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//N/A (Fixed)
DiffPowerSetting=0//FF6-60 deg (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
DiffCoastSetting=2//FF6-45 deg (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
DiffPreloadSetting=17//85 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//N/A (Fixed)
FrontDiffPowerSetting=0//0% (Fixed)
FrontDiffCoastSetting=0//0% (Fixed)
FrontDiffPreloadSetting=0//1 (Fixed)
RearSplitSetting=0// 0.0:100.0 (Fixed to RWD)
GearAutoUpShiftSetting=0//Off (Fixed)
GearAutoDownShiftSetting=0//Off (Fixed)

[FRONTLEFT]
CamberSetting=11//-1.5 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=3//0.3 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=5//150N/mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=10//4.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=11//-1.5 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=3//0.3 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=5//150N/mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=10//4.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=24//7.0 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=24//7.0 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)`,

    'GTE': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(0,0,0,0)
//UpgradeClass=
//Aero package=0
//Note: settings commented out if using the default

[GENERAL]
Notes=""
Symmetric=1
//CGHeightSetting=0//Non-adjustable
//CGRightSetting=0//Non-adjustable
//CGRearSetting=0//Non-adjustable
//WedgeSetting=0//N/A
FuelSetting=33//34L (13laps)
//FuelCapacitySetting=0//+0L (0laps)
//NumPitstopsSetting=0//
//Pitstop1Setting=49//N/A
//Pitstop2Setting=49//N/A
//Pitstop3Setting=49//N/A

[LEFTFENDER]
//FenderFlareSetting=0//Standard

[RIGHTFENDER]
//FenderFlareSetting=0//Standard

[FRONTWING]
//FWSetting=0//Standard

[REARWING]
RWSetting=2//P3

[BODYAERO]
//WaterRadiatorSetting=0//No tape
//OilRadiatorSetting=0//No tape
//BrakeDuctSetting=1//33%
//BrakeDuctRearSetting=1//33%

[SUSPENSION]
//FrontWheelTrackSetting=0//Non-adjustable
//RearWheelTrackSetting=0//Non-adjustable
//FrontAntiSwaySetting=5//P5
RearAntiSwaySetting=3//Balanced Default
//FrontToeInSetting=6//-0.23 deg
//FrontToeOffsetSetting=0//N/A
RearToeInSetting=12//0.47 deg
//RearToeOffsetSetting=0//N/A
//LeftCasterSetting=0//Non-adjustable
//RightCasterSetting=0//Non-adjustable
//LeftTrackBarSetting=0//N/A
//RightTrackBarSetting=0//N/A
//Front3rdPackerSetting=0//N/A
//Front3rdSpringSetting=0//Detached
//Front3rdTenderSpringSetting=0//Detached
//Front3rdTenderTravelSetting=0//Detached
//Front3rdSlowBumpSetting=0//N/A
//Front3rdFastBumpSetting=0//N/A
//Front3rdSlowReboundSetting=0//N/A
//Front3rdFastReboundSetting=0//N/A
//Rear3rdPackerSetting=0//N/A
//Rear3rdSpringSetting=0//Detached
//Rear3rdTenderSpringSetting=0//Detached
//Rear3rdTenderTravelSetting=0//Detached
//Rear3rdSlowBumpSetting=0//N/A
//Rear3rdFastBumpSetting=0//N/A
//Rear3rdSlowReboundSetting=0//N/A
//Rear3rdFastReboundSetting=0//N/A
//ChassisAdj00Setting=0//N/A
//ChassisAdj01Setting=0//N/A
//ChassisAdj02Setting=0//N/A
//ChassisAdj03Setting=0//N/A
//ChassisAdj04Setting=0//N/A
//ChassisAdj05Setting=0//N/A
//ChassisAdj06Setting=0//N/A
//ChassisAdj07Setting=0//N/A
//ChassisAdj08Setting=0//N/A
//ChassisAdj09Setting=0//N/A
//ChassisAdj10Setting=0//N/A
//ChassisAdj11Setting=0//N/A

[CONTROLS]
//SteerLockSetting=6//540 (18) deg
RearBrakeSetting=17//52.8:47.2
//BrakeMigrationSetting=0// 0.0
//BrakePressureSetting=40//80 kgf (100%)
//HandfrontbrakePressSetting=0//N/A
//HandbrakePressSetting=0//N/A
//TCSetting=0//Available
//ABSSetting=0//N/A
TractionControlMapSetting=6//6
TCPowerCutMapSetting=2//2
//TCSlipAngleMapSetting=4//4
//AntilockBrakeSystemMapSetting=0//N/A

[ENGINE]
//RevLimitSetting=0//7,400
//EngineBoostSetting=0//N/A
//RegenerationMapSetting=0//0%
//ElectricMotorMapSetting=0//
EngineMixtureSetting=1//Race lean
//EngineBrakingMapSetting=0//N/A

[DRIVELINE]
//FinalDriveSetting=0//3.664
//ReverseSetting=0//3.083
Gear1Setting=0//2.067
Gear2Setting=0//1.706
Gear3Setting=0//1.368
Gear4Setting=0//1.143
Gear5Setting=0//1.000
Gear6Setting=0//0.889
//RatioSetSetting=0//Standard
//DiffPumpSetting=0//N/A
//DiffPowerSetting=0//Non-adjustable
//DiffCoastSetting=0//Non-adjustable
DiffPreloadSetting=18//90 Nm
//FrontDiffPumpSetting=0//0%
//FrontDiffPowerSetting=0//0%
//FrontDiffCoastSetting=0//0%
//FrontDiffPreloadSetting=0//1
//RearSplitSetting=0//RWD
//GearAutoUpShiftSetting=0//Off
//GearAutoDownShiftSetting=0//Off

[FRONTLEFT]
CamberSetting=28//-2.2 deg
//PressureSetting=0//140 kPa
//PackerSetting=20//2.0 cm
SpringSetting=5//220 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=0//5.0 cm
SlowBumpSetting=8//8
FastBumpSetting=10//10
SlowReboundSetting=10//10
FastReboundSetting=10//10
//BrakeDiscSetting=0//3.56 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//

[FRONTRIGHT]
CamberSetting=28//-2.2 deg
//PressureSetting=0//140 kPa
//PackerSetting=20//2.0 cm
SpringSetting=5//220 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=0//5.0 cm
SlowBumpSetting=8//8
FastBumpSetting=10//10
SlowReboundSetting=10//10
FastReboundSetting=10//10
//BrakeDiscSetting=0//3.56 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//

[REARLEFT]
CamberSetting=33//-1.2 deg
//PressureSetting=0//140 kPa
PackerSetting=25//2.5 cm
SpringSetting=1//140 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=22//7.2 cm
SlowBumpSetting=7//7
FastBumpSetting=7//7
SlowReboundSetting=7//7
FastReboundSetting=7//7
//BrakeDiscSetting=0//3.20 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//

[REARRIGHT]
CamberSetting=33//-1.2 deg
//PressureSetting=0//140 kPa
PackerSetting=25//2.5 cm
SpringSetting=1//140 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=22//7.2 cm
SlowBumpSetting=7//7
FastBumpSetting=7//7
SlowReboundSetting=7//7
FastReboundSetting=7//7
//BrakeDiscSetting=0//3.20 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//`,

    'GT3': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(3276,0,0,0) // Fixed to car's upgrade package
[GENERAL]
Notes=""
Symmetric=1
//CGHeightSetting=0//Non-adjustable (Fixed)
//CGRightSetting=0//Non-adjustable (Fixed)
//CGRearSetting=0//Non-adjustable (Fixed)
//WedgeSetting=0//N/A (Fixed)
FuelSetting=92//0.93 (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//93.0l (22.5 laps) (Fixed)
VirtualEnergySetting=100//100% (22.0 laps) (Fixed)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=59//N/A (Fixed)
Pitstop2Setting=59//N/A (Fixed)
Pitstop3Setting=59//N/A (Fixed)

[LEFTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
//FWSetting=0//N/A (Fixed)

[REARWING]
RWSetting=2//P3 (Min: 0, Max: 14) (MUST BE OVERWRITTEN) // GT3 RW: 0-14 (P1-P15 in game UI)

[BODYAERO]
WaterRadiatorSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
OilRadiatorSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=2//40mm (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=7//P7 (dur) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=4//P4 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FrontToeInSetting=7//-0.117 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=8//0 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
//Front3rdPackerSetting=0//N/A (Fixed)
//Front3rdSpringSetting=0//N/A (Fixed)
//Front3rdTenderSpringSetting=0//Détaché (Fixed)
//Front3rdTenderTravelSetting=0//Détaché (Fixed)
//Front3rdSlowBumpSetting=0//N/A (Fixed)
//Front3rdFastBumpSetting=0//N/A (Fixed)
//Front3rdSlowReboundSetting=0//N/A (Fixed)
//Front3rdFastReboundSetting=0//N/A (Fixed)
//Rear3rdPackerSetting=0//N/A (Fixed)
//Rear3rdSpringSetting=0//N/A (Fixed)
//Rear3rdTenderSpringSetting=0//Détaché (Fixed)
//Rear3rdTenderTravelSetting=0//Détaché (Fixed)
//Rear3rdSlowBumpSetting=0//N/A (Fixed)
//FastBumpSetting=0//N/A (Fixed)
//SlowReboundSetting=0//N/A (Fixed)
//FastReboundSetting=0//N/A (Fixed)

[CONTROLS]
SteerLockSetting=4//380° (11.2°) (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
RearBrakeSetting=21//51.8:48.2 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
//BrakeMigrationSetting=0// 0.0 (Fixed)
//BrakePressureSetting=80//120 kgf (100%) (Fixed)
//HandfrontbrakePressSetting=0//N/A (Fixed)
//HandbrakePressSetting=0//N/A (Fixed)
//TCSetting=0//Disponible (Fixed)
//ABSSetting=0//Disponible (Fixed)
//TractionControlMapSetting=8//8 (Fixed)
TCPowerCutMapSetting=3//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//TCSlipAngleMapSetting=10//10 (Fixed)
AntilockBrakeSystemMapSetting=11//11 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)

[ENGINE]
//RevLimitSetting=0//9,400 (Fixed)
//EngineBoostSetting=0//N/A (Fixed)
//RegenerationMapSetting=0//0% (Fixed)
ElectricMotorMapSetting=0//Not Applicable (N/A for Non-Hybrid) (Fixed)
//EngineMixtureSetting=1//Race (Fixed)
//EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=0//Fixed (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ReverseSetting=0//Fixed
Gear1Setting=0//Fixed (~95 km/h / ~59 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//Fixed (~130 km/h / ~81 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//Fixed (~160 km/h / ~99 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//Fixed (~190 km/h / ~118 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//Fixed (~220 km/h / ~137 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//Fixed (~250 km/h / ~155 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Longest ratio.
RatioSetSetting=0//Short (Min: 0, Max: 1) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//Non-adjustable (Fixed)
DiffPowerSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
DiffCoastSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
DiffPreloadSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//0% (Fixed)
FrontDiffPowerSetting=0//0% (Fixed)
FrontDiffCoastSetting=0//0% (Fixed)
FrontDiffPreloadSetting=0//1 (Fixed)
RearSplitSetting=0//RWD (Fixed)
GearAutoUpShiftSetting=0//Non (Fixed)
GearAutoDownShiftSetting=0//Non (Fixed)

[FRONTLEFT]
CamberSetting=26//-1.80 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=9//0.9 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=3//4 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Standard (Fixed)
//SpringRubberSetting=0//N/A (Fixed)
//RideHeightSetting=0//5.0 cm (MUST BE OVERWRITTEN)
SlowBumpSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//12 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.56 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=26//-1.80 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=9//0.9 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=3//4 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Standard (Fixed)
//SpringRubberSetting=0//N/A (Fixed)
//RideHeightSetting=0//5.0 cm (MUST BE OVERWRITTEN)
SlowBumpSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//12 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.56 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=25//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=14//1.4 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=1//2 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=16//6.6 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=7//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=25//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=14//1.4 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=1//2 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=16//6.6 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=7//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)`
};

// 8. Define a route for AI setup requests
app.post('/generate-setup', async (req, res) => {
    // Safely destructure all possible values from the request body
    const {
        car, track, request, selectedCarCategory,
        selectedCarDisplay, selectedTrackDisplay, setupGoal,
        sessionGoal, selectedWeather, trackTemp, specificRequest, driverFeedback
    } = req.body;

    // Validate essential parameters
    if (!car || !track || !setupGoal || !selectedCarCategory) {
        return res.status(400).json({
            error: "Please provide Car, Track, Setup Goal, and Car Category details."
        });
    }

    // Handle potential category key mismatch
    let finalCategory = selectedCarCategory;
    if (selectedCarCategory === 'LMGT3' && LMU_VEH_TEMPLATES['GT3']) {
        finalCategory = 'GT3';
    } else if (selectedCarCategory === 'GT3' && !LMU_VEH_TEMPLATES['GT3']) { // Check if 'GT3' is missing
        finalCategory = 'GTE'; // Fallback if needed, or handle error
    }

    let exampleTemplate = LMU_VEH_TEMPLATES[finalCategory];
    if (!exampleTemplate) {
        return res.status(400).json({
            error: `No .VEH template found for car category: ${finalCategory}. Ensure selected car has a valid category.`
        });
    }

    // --- CRITICAL: LE MANS SPECIFIC OVERRIDE LOGIC (Server-Side Enforcement) ---
    // This ensures Le Mans gets the absolute lowest drag settings regardless of AI's broader interpretation.
    let finalExampleTemplate = exampleTemplate; // Start with the chosen template

    const trackOverrides = (trackName, template) => {
        let overriddenTemplate = template;
        // Generic regex to replace a setting's number while preserving its trailing comment
        const replaceSetting = (settingName, newValue, regexFlags = 'm') => {
            const regex = new RegExp(`^(${settingName}=)\\d+(.*)`, regexFlags);
            overriddenTemplate = overriddenTemplate.replace(regex, `$1${newValue}$2`);
        };

        const replaceSectionSetting = (section, settingName, newValue, regexFlags = 'm') => {
            const regex = new RegExp(`^(${section}[\\s\\S]*?${settingName}=)\\d+(.*)`, regexFlags);
            overriddenTemplate = overriddenTemplate.replace(regex, `$1${newValue}$2`);
        };


        if (trackName === "Circuit de la Sarthe (Le Mans)" || trackName === "Autodromo Nazionale Monza") {
            const minAeroSetting = 0;
            const note = trackName === "Circuit de la Sarthe (Le Mans)" ?
                'Notes="Le Mans override applied: Absolute minimum drag prioritized. All aero, ride height, and radiators minimized for top speed. Gearing set to longest possible configuration."' :
                'Notes="Monza override applied: Absolute minimum drag prioritized. All aero, ride height, and radiators minimized for top speed. Gearing set to longest possible configuration."';

            replaceSectionSetting('\\[FRONTWING\\]', 'FWSetting', minAeroSetting);
            replaceSectionSetting('\\[REARWING\\]', 'RWSetting', minAeroSetting);

            let maxFinalDrive;
            if (finalCategory === 'Hypercar') maxFinalDrive = 7;
            else if (finalCategory === 'LMP2') maxFinalDrive = 5;
            else if (finalCategory === 'GT3' || finalCategory === 'GTE') maxFinalDrive = 10;

            if (maxFinalDrive !== undefined) {
                replaceSectionSetting('\\[DRIVELINE\\]', 'FinalDriveSetting', maxFinalDrive);
            }
            overriddenTemplate = overriddenTemplate.replace(/^(Gear\dSetting=)\d+(.*)/gm, `$11$2`);
            replaceSetting('RatioSetSetting', 1);

            // For Radiators/Ducts, a HIGHER index means more closed (less drag)
            // LMU Hypercar: Water/Oil Radiator max 4, Brake Ducts max 3
            // So we set them to their max values for minimum drag.
            replaceSetting('WaterRadiatorSetting', 4);
            replaceSetting('OilRadiatorSetting', 4);
            replaceSetting('BrakeDuctSetting', 3);
            replaceSetting('BrakeDuctRearSetting', 3);

            overriddenTemplate = overriddenTemplate.replace(/^(RideHeightSetting=)\d+(.*)/gm, `$10$2`);
            overriddenTemplate = overriddenTemplate.replace(/Notes=""/, note);

        } else if (trackName === "Sebring International Raceway") {
            const note = 'Notes="Sebring override applied: Prioritized maximum bump absorption. Dampers and Anti-Roll Bars set to softest. Ride height increased to absorb bumps."';

            // Set dampers to very soft values (e.g., 0 or 1)
            // We specifically target FAST dampers for bumps.
            overriddenTemplate = overriddenTemplate.replace(/^(Front3rdFastBumpSetting=)\d+(.*)/m, '$10$2');
            overriddenTemplate = overriddenTemplate.replace(/^(Front3rdFastReboundSetting=)\d+(.*)/m, '$10$2');
            overriddenTemplate = overriddenTemplate.replace(/^(Rear3rdFastBumpSetting=)\d+(.*)/m, '$10$2');
            overriddenTemplate = overriddenTemplate.replace(/^(Rear3rdFastReboundSetting=)\d+(.*)/m, '$10$2');
            overriddenTemplate = overriddenTemplate.replace(/^(FastBumpSetting=)\d+(.*)/gm, '$10$2');
            overriddenTemplate = overriddenTemplate.replace(/^(FastReboundSetting=)\d+(.*)/gm, '$10$2');

            // Set ARBs to very soft values
            replaceSetting('FrontAntiSwaySetting', 1);
            replaceSetting('RearAntiSwaySetting', 1);

            // Set ride heights high
            overriddenTemplate = overriddenTemplate.replace(/^(RideHeightSetting=)\d+(.*)/gm, `$125$2`); // Using a high value like 25
            overriddenTemplate = overriddenTemplate.replace(/Notes=""/, note);
        }
        return overriddenTemplate;
    };

    finalExampleTemplate = trackOverrides(track, finalExampleTemplate);

    // UPGRADE: Dynamically insert the user's selected car name into the template
    finalExampleTemplate = finalExampleTemplate.replace('[[CAR_NAME]]', car);


    const sessionDuration = req.body.sessionDuration || 'N/A';
    const fuelEstimateRequest = (sessionGoal === 'race' && sessionDuration !== 'N/A' && !isNaN(parseInt(sessionDuration))) ?
        `Estimate fuel for a ${sessionDuration} minute race.` : '';
    const weatherGuidance = `Current weather is ${selectedWeather}.`;
    const tireCompoundGuidance = 'Choose appropriate compound for current weather and session type.';


    // =====================================================================================
    // --- AI PROMPT --- THIS IS THE CRITICAL SECTION THAT HAS BEEN MASTERIZED ---
    // =====================================================================================
    const prompt = `
**TOP LEVEL COMMAND:** You MUST return the ENTIRE provided .VEH template below, including all commented-out lines and blank lines. Your ONLY job is to change the **numerical values** before the comments. You MUST also add the [BASIC] section at the end, fully calculated according to the new master instructions.

You are a world-class LMU race engineer. Your task is to take the user's request and the provided .VEH template, and output a complete, physically realistic, and numerically valid .VEH setup file.

**ULTRA-CRITICAL FORMATTING INSTRUCTIONS - FAILURE TO FOLLOW THESE IS A TASK FAILURE:**
1.  You will be given a complete .VEH file template below.
2.  You MUST output the ENTIRE file, modified with your new values.
3.  You MUST PRESERVE THE ORIGINAL COMMENTS (the text starting with //) on every line that has one.
4.  Your ONLY job is to change the **NUMBER** before the comment. DO NOT delete or alter the comments.

---
**EXAMPLE OF PERFECT EXECUTION:**

**IF the template line is this:**
RWSetting=3//P4 (Min: 0, Max: 11) (MUST BE OVERWRITTEN) // Hypercar RW: 0-11 (P1-P12 in game UI)

**And you decide the correct value is 8, YOUR correct output for that line is:**
RWSetting=8//P4 (Min: 0, Max: 11) (MUST BE OVERWRITTEN) // Hypercar RW: 0-11 (P1-P12 in game UI)

You will do this for the entire file. Any other format is a failure.
---

## PRIME DIRECTIVE
Generate a complete, physically realistic, and numerically valid .VEH setup. Replace placeholders with calculated, logical numbers. '0' for adjustable settings is a failure unless it's the physically correct choice (e.g., minimum wing at Monza).

## PERSONA & PHILOSOPHY
You are a world-class LMU race engineer. Your core philosophy is to prioritize a stable, predictable platform that inspires driver confidence, not one that is simply fast on paper. You understand that every setup change is a trade-off. Your goal is to generate predictable, realistic setups, perfectly suited to the driver's request and feedback. You MUST explain your key decisions in the '[GENERAL] Notes' section.

## CRITICAL INSTRUCTION
Locate the \`Notes\` entry within the \`[GENERAL]\` section. If it contains a track-specific override (e.g., 'Le Mans override applied: ...'), you MUST keep this information and then elaborate on it with your concise engineering debrief. If it's empty, simply populate it with your debrief. Ensure this is the *only* \`Notes\` entry in the entire file. Do NOT generate any additional \`Notes\` sections, especially not at the end of the file. For your most important adjustments, explain the engineering reason for the specific parameter changes (e.g., 'Increased RearCamberSetting to reduce oversteer on exit', 'Softened front fast dampers for better bump absorption at Sebring').

## THOUGHT PROCESS & HIERARCHY
1.  **Session Type (Qualifying vs. Race):** Dictates overall setup philosophy.
2.  **Driver Feedback is KING:** Address 'Driver Problem to Solve' first. Consult 'DRIVER FEEDBACK TROUBLESHOOTING MATRIX'. Apply Primary/Secondary solutions. All other decisions must align with solving the driver's issue.
3.  **Track DNA & Weather:** Analyze the track's unique demands ('ENHANCED TRACK DNA DATABASE') and weather conditions. Apply baseline decisions and mention any necessary compromises in your notes.
4.  **Car Architecture:** Apply specific adjustments based on the car's inherent traits ('CAR ARCHITECTURE PHILOSOPHY').
5.  **Overall Setup Goal:** Use the driver's 'Setup Goal' ('Safe', 'Balanced', 'Aggressive') from the 'LMU SETUP PHILOSOPHY DIAL' to fine-tune all settings.
6.  **Generate [BASIC] Parameters (MANDATORY):** You MUST dynamically calculate and GENERATE the [BASIC] section at the end of the .VEH file. This high-level summary is critical for users to understand the setup's intent at a glance. It is NOT in the template; it must be fully derived.
    - Every parameter ('Downforce', 'Balance', 'Ride', 'Gearing') MUST be a uniquely calculated float (e.g., 0.125000).
    - Outputting a generic default like 0.500000 is a critical failure, UNLESS your calculation genuinely results in that optimal value.
    - **'Downforce'**: Represents overall aero grip from 0.0 (min) to 1.0 (max). Calculate this as the average of the normalized wing settings: \`((FWSetting / FW_Max) + (RWSetting / RW_Max)) / 2\`. Low-drag setups (Le Mans) should be low (0.0 - 0.15). High-downforce tracks (Portimão) should be high (0.65 - 0.95).
    - **'Balance'**: Represents aero/mechanical balance from 0.0 (oversteer) to 1.0 (understeer). Start with aero balance: \`AeroBalance = (FWSetting / FW_Max) / ((FWSetting / FW_Max) + (RWSetting / RW_Max))\`. **Adjust this baseline for mechanical balance. Stiffer front ARB vs. rear pushes value UP (more understeer). Stiffer rear ARB pushes it DOWN (more oversteer).** Aggressive setups are low (0.15-0.35). Stable setups are high (0.65-0.85).
    - **'Ride'**: Represents suspension compliance from 0.0 (stiff/low) to 1.0 (soft/high). Calculate this by averaging the normalized values of: Ride Height (value/max), Spring Stiffness (value/max), and Fast Bump Damper settings (value/max). A stiff car for a smooth track should be low (0.1-0.3). A soft car for a bumpy track (Sebring) must be high (0.8-0.95).
    - **'Gearing'**: Represents acceleration (0.0) vs. top speed (1.0). Calculate as a weighted average: \`0.7 * (FinalDriveSetting / FinalDrive_Max) + 0.3 * (RatioSetSetting)\`. Value near 1.0 for top speed tracks. Value near 0.1 for acceleration tracks.
    - **'Custom'**: Must always be 1.
7.  **Engineer's Debrief:** Ensure the \`Notes\` entry in the \`[GENERAL]\` section (as per 'CRITICAL INSTRUCTION') is complete and accurate.

// =====================================================================================
// --- START OF MASTERIZED KNOWLEDGE BASE (UPGRADED June 2025) ---
// =====================================================================================

## LMU SETUP FUNDAMENTALS (DEEP DIVE)
- **The Platform Concept:** The car's chassis is a 'platform'. All setup changes aim to keep this platform stable and predictable. A stable platform allows the aerodynamics to work efficiently and gives the driver confidence. Key elements are pitch (braking/acceleration), roll (cornering), and heave (vertical movement over bumps). Your goal is to control these motions.
- **Pyramid of Grip:** Grip starts at the tires. 1. **Tires:** Must be kept in their optimal temperature and pressure window with the largest possible contact patch on the road. 2. **Suspension:** Manages the tire's contact with the road. It controls weight transfer and absorbs bumps. 3. **Aerodynamics:** Pushes the car onto the track, generating huge amounts of grip at speed. Aero is useless if the suspension can't keep the tires on the asphalt. All setup decisions must respect this hierarchy.
- **The Law of Trade-Offs:** Every single change you make has a consequence. More rear wing gives more cornering grip but reduces top speed. Softer springs absorb bumps better but make the car less responsive. Your job is to find the best compromise for the specific car, track, and driver.

// --- MASTERIZED KNOWLEDGE FOR [FRONTLEFT], [FRONTRIGHT], [REARLEFT], [REARRIGHT] ---
## SUSPENSION, GEOMETRY & TIRE PHILOSOPHY
This is where mechanical grip is born. Your settings here dictate how the tire meets the road.

### [BODYAERO] - COOLING & DRAG STRATEGY
- **Radiators & Brake Ducts:** These settings (\`WaterRadiatorSetting\`, \`OilRadiatorSetting\`, \`BrakeDuctSetting\`) are a direct trade-off between engine/brake cooling and aerodynamic drag.
- **Principle:** More cooling (LOWER index number, more open) creates more drag. Less cooling (HIGHER index number, more closed/taped) reduces drag and increases top speed.
- **Track-Specific Application:**
    - **Hot Tracks (Bahrain, Sebring >25C):** You need more cooling. Use lower index values (e.g., 1-2) to prevent overheating.
    - **Cold Tracks (Spa <15C):** You can gain "free" top speed. Use higher index values (e.g., 3-4, depending on max) to close the ducts.
    - **Heavy Braking Tracks (Monza, Fuji):** Require more brake cooling (\`BrakeDuctSetting\` at a lower index) to prevent brake fade, even if the ambient temperature is cool.

### [FRONTWING] & [REARWING] - AERO BALANCE
- **Function:** These are your primary tools for high-speed balance. They directly control the Center of Pressure (CoP).
- **Aero Balance:** The ratio of front to rear wing (\`FWSetting\` vs. \`RWSetting\`) determines understeer or oversteer at high speed.
    - **More Front Wing (or less Rear Wing):** Shifts CoP forward -> Increases front grip -> More rotation/oversteer.
    - **More Rear Wing (or less Front Wing):** Shifts CoP rearward -> Increases rear grip -> More stability/understeer.
- **Rake (Ride Height Difference):** Aero downforce is hugely affected by ride height. A higher rear ride height compared to the front (positive rake) increases the effectiveness of the car's floor and diffuser, adding overall downforce and typically shifting the balance slightly forward. This must be managed with spring stiffness.

### SUSPENSION & DAMPING
- **Springs (\`SpringSetting\`) & Packers (\`PackerSetting\`):**
    - **Springs:** Support the car under heavy aerodynamic load. Stiffer springs are mandatory on high-downforce tracks (Spa, Portimão) to prevent the car from bottoming out at speed. Softer springs are used on bumpy tracks (Sebring) to improve compliance.
    - **Packers:** These are bump stops that limit suspension travel. On very smooth tracks, you can use more packers to run a lower ride height. On bumpy tracks, you need minimal packers to allow for maximum suspension travel.
- **Dampers (\`SlowBump\`, \`FastBump\`, \`SlowRebound\`, \`FastRebound\`):**
    - **Slow-Speed (Bump/Rebound):** Controls the chassis's response to driver inputs (braking, turning, throttle). Stiffer slow dampers = sharp, responsive car. Softer slow dampers = smoother, more forgiving car.
    - **Fast-Speed (Bump/Rebound):** Controls the wheels' response to track imperfections (kerbs, bumps). **CRITICAL RULE:** For a bumpy track like Sebring, you MUST use very soft \`FastBump\` settings (0-2) to allow the wheel to absorb the bump without upsetting the chassis. On a smooth track, they can be stiffer for platform control.

### TIRES & GEOMETRY
- **Tire Pressure (\`PressureSetting\`):** The goal is to achieve optimal operating temperature and an even temperature spread across the tire surface. Start with a baseline and adjust based on telemetry. Higher pressure = less rolling resistance, slower heat build-up. Lower pressure = more grip, faster heat build-up.
- **Camber (\`CamberSetting\`):** More negative camber increases grip in long-duration corners by keeping the outside tire flat. The trade-off is reduced braking and traction performance in a straight line. Too much will overheat the inside edge of the tire.
- **Toe (\`FrontToeInSetting\`, \`RearToeInSetting\`):**
    - **Front:** Toe-out (a negative value in the setup file's comment) helps the car turn-in sharply but can make it unstable on straights.
    - **Rear:** Toe-in (a positive value) is ESSENTIAL for stability under braking and acceleration. Nearly all race setups use some degree of rear toe-in.

// --- MASTERIZED [DRIVELINE] GUIDE --- //
## DIFFERENTIAL & GEARING: PUTTING POWER TO THE GROUND
- The differential (\`DiffPowerSetting\`, \`DiffCoastSetting\`, \`DiffPreloadSetting\`) is your main tool for managing stability on corner entry and traction on corner exit.

### DIFFERENTIAL DEEP DIVE
- **Power Lock (\`DiffPowerSetting\`):** Controls how much the rear wheels are locked together on-throttle.
    - **High Value (More Lock):** Maximizes straight-line traction, very stable on exit. Prevents inside wheel spin. Essential for bumpy and traction-limited tracks.
    - **Low Value (Less Lock):** Allows wheels to rotate at different speeds, helping the car turn with the throttle. Can make the car "loose" and prone to wheelspin.
- **Coast Lock (\`DiffCoastSetting\`):** Controls locking when off-throttle (braking and turn-in).
    - **High Value (More Lock):** Makes the car very stable on corner entry. Resists rotation. Excellent for high-speed, flowing corners.
    - **Low Value (Less Lock):** "Frees up" the rear of the car, reducing entry understeer and helping it point into the corner. Too low can cause "lift-off oversteer."
- **Preload (\`DiffPreloadSetting\`):** The base amount of lock always present. Higher preload makes the transition between power and coast phases smoother and more predictable, increasing overall stability, which is vital for bumpy tracks.

### Track Archetype Differential Philosophy:
- **Traction-Limited & Bumpy (Sebring, Portimão):**
    - **\`DiffPowerSetting\` -> HIGH:** Essential to put power down.
    - **\`DiffPreloadSetting\` -> HIGH:** CRITICAL to prevent erratic behavior over bumps.
    - **\`DiffCoastSetting\` -> MEDIUM/LOW:** To help the car rotate in slow corners.
- **High-Speed & Flowing (Le Mans, Monza, Spa):**
    - **\`DiffCoastSetting\` -> HIGH:** #1 priority for high-speed entry stability.
    - **\`DiffPowerSetting\` -> LOW/MEDIUM:** Prevents exit understeer when momentum is key.
    - **\`DiffPreloadSetting\` -> MEDIUM:** Enough to be smooth without masking feedback.

### [DRIVELINE] GEARING STRATEGY
- Gearing is a balance between acceleration and top speed.
- **\`FinalDriveSetting\` & \`RatioSetSetting\`:** These set your overall gearing profile. A higher index \`FinalDriveSetting\` and a \`RatioSetSetting\` of '1' (Long) are for top-speed tracks. Lower values are for acceleration tracks.
- **Individual Gears (\`GearXSetting\`):** In LMU, these are often just '0' (Shortest) or '1' (Longest). Your primary tool is the Final Drive. You must ensure the top gear allows the car to reach the end of the longest straight without hitting the rev limiter too early.

// --- MASTERIZED [ENGINE] & [CONTROLS] GUIDE --- //
## ENGINE MANAGEMENT & DRIVER INTERFACE

### [ENGINE] SETTINGS
- **Engine Mixture (\`EngineMixtureSetting\`):**
    - **Qualifying:** Use the richest/most powerful mode (often index 0).
    - **Race:** Use a leaner mode (index 1 or 2) to save fuel over a stint. The performance loss is often minimal compared to the time gained by a shorter pit stop.
- **Hybrid System (Hypercars - \`RegenerationMapSetting\`, \`ElectricMotorMapSetting\`):**
    - See the detailed **HYBRID POWER UNIT (HPU) STRATEGY** section.
- **Engine Braking (\`EngineBrakingMapSetting\` - if available):** This setting adjusts the off-throttle braking effect from the engine. Higher values create more braking, helping to slow the car and can increase stability on entry, acting similarly to a higher \`DiffCoastSetting\`. Lower values provide a "freer" feel.

### [CONTROLS] SETTINGS
- **Steering Lock (\`SteerLockSetting\`):** A smaller steering lock (e.g., 450 degrees) makes the steering very direct and quick, ideal for aggressive driving and tight hairpins. A larger lock (e.g., 540 degrees) is slower and smoother, making the car less "twitchy" and easier to control.
- **Brake Bias (\`RearBrakeSetting\`):** This value shifts brake force front-to-rear. A higher numerical value does NOT mean more rear bias, it's car-dependent; refer to the in-game UI's percentage. Moving bias rearward (e.g., to 47%) helps rotation but increases instability. Moving it forward (e.g., to 53%) increases stability but can cause understeer.
- **Brake Pressure (\`BrakePressureSetting\`):** 100% pressure provides maximum stopping power but increases the risk of locking the tires. For long races or for drivers without load-cell pedals, reducing pressure to 95-98% can provide a larger modulation window, preventing lockups and flat spots.
- **Traction Control / ABS (\`TractionControlMapSetting\`, \`AntilockBrakeSystemMapSetting\`, etc.):** These are driver aids.
    - **For Qualifying:** Use the lowest possible settings (e.g., 1-3) that you can handle to minimize intervention and maximize performance.
    - **For Races (especially wet):** Use higher, safer settings (e.g., 5-8) to reduce mistakes, save tires, and maintain consistency when fatigued.

## ENHANCED TRACK DNA DATABASE & SETUP IMPLICATIONS
- **Circuit de la Sarthe (Le Mans):**
    - **DNA:** A unique high-speed monster. Massive straights demanding minimal drag, but with critical high-speed corners (Porsche Curves) and heavy braking zones (Mulsanne chicanes) that require stability.
    - **[BODYAERO], [FRONTWING], [REARWING]:** Absolute minimum drag is non-negotiable. Set \`RWSetting\` to 0 or 1, \`FWSetting\` to its minimum (0). Close radiators and brake ducts (\`WaterRadiatorSetting\`, \`OilRadiatorSetting\`, \`BrakeDuctSetting\` to their highest index values) as much as track temperature allows to reduce drag.
    - **[DRIVELINE]:** Maximum top speed is the goal. Use the longest possible \`FinalDriveSetting\` and set all \`GearXSetting\` to 1. \`DiffCoastSetting\` should be HIGH to maintain rear stability when lifting off at 300km/h for the chicanes. \`DiffPowerSetting\` can be medium-low to prevent exit understeer from the slow chicanes and Arnage.
    - **[SUSPENSION]:** Low ride height (\`RideHeightSetting\` near 0) to minimize drag. Run stiff springs and stiff slow bump/rebound to maintain a stable aero platform at high speed. However, fast dampers can be slightly softer to absorb the track's older, bumpy sections, especially on the Mulsanne straight. Use minimal toe angles to reduce drag.

- **Sebring International Raceway:**
    - **DNA:** Notoriously bumpy. A test of mechanical grip and suspension compliance. The old concrete slabs punish overly stiff setups.
    - **[SUSPENSION]:** Maximize mechanical grip and compliance. This means SOFT suspension. \`RideHeightSetting\` must be high (e.g., 20-30). \`SpringSetting\` should be very soft. Most importantly, \`FastBumpSetting\` and \`FastReboundSetting\` must be near their minimum (0-2) to allow the wheels to absorb the brutal bumps. Slow dampers can be slightly stiffer to control the car's body motion in the few smoother corners.
    - **[DRIVELINE]:** The track is traction-limited due to the bumps. Use a HIGH \`DiffPowerSetting\` to get power down and a HIGH \`DiffPreloadSetting\` to stabilize the differential over the slabs. Gearing should be short (\`FinalDriveSetting\` low, \`GearXSetting\` 0) for acceleration out of the hairpin and other slow corners.
    - **[AERO]:** Downforce is still important for the faster sections, but mechanical grip is king. A medium downforce setup is a good compromise.

- **Spa-Francorchamps:**
    - **DNA:** A classic driver's circuit with high-speed flowing corners, significant elevation changes (Eau Rouge/Raidillon), a long straight, and a slow-speed chicane. Requires a balanced setup.
    - **[SUSPENSION]:** The compression in Eau Rouge demands stiff front springs and front \`SlowBumpSetting\` to prevent the car from bottoming out. Ride height needs to be carefully managed - low enough for aero efficiency, but high enough to clear the compression. The rest of the track rewards a car that can change direction quickly, so anti-roll bars will be key to tuning the balance.
    - **[AERO]:** Medium-to-high downforce is needed for stability and speed through corners like Pouhon and Blanchimont. You trade top speed on the Kemmel Straight for lap time through Sector 2.
    - **[DRIVELINE]:** Gearing needs to be a compromise. Long enough for the Kemmel Straight, but short enough for the La Source hairpin and Bus Stop chicane. A high \`DiffCoastSetting\` is crucial for stability on high-speed corner entries.

- **Autodromo Nazionale Monza:**
    - **DNA:** The "Temple of Speed". The absolute lowest drag setup is required. The main challenge is finding stability under extreme braking for the tight chicanes and having enough mechanical grip to ride the kerbs effectively.
    - **[AERO]:** Even lower drag than Le Mans. \`RWSetting\` and \`FWSetting\` must be at their absolute minimum (0). All ducts must be as closed as possible.
    - **[SUSPENSION]:** Suspension must be set up to handle aggressive kerb-riding at the chicanes. While the car needs to be low for low drag, you need compliant fast damping and potentially slightly higher \`PackerSetting\` to avoid damage and instability over the kerbs.
    - **[CONTROLS]:** Brake bias (\`RearBrakeSetting\`) is critical. Move it forward for stability when braking from 330km/h+.
    - **[DRIVELINE]:** Longest gearing possible. Use a HIGH \`DiffCoastSetting\` for maximum braking stability. \`DiffPowerSetting\` should be relatively low to allow the car to rotate sharply in the chicanes and get back on the power without understeer.

- **Fuji Speedway:**
    - **DNA:** A track of two distinct halves: a very long main straight and a tight, technical final sector. This is the ultimate compromise track.
    - **[AERO]:** This is the key trade-off. Do you run low wing for the straight and struggle in Sector 3, or high wing for Sector 3 and get passed on the straight? A balanced or slightly lower-downforce setup is common.
    - **[DRIVELINE]:** Gearing is a compromise. You need a long top gear for the straight, but good acceleration for the slow corners. The differential should be tuned for traction out of the final corner, meaning a relatively high \`DiffPowerSetting\`.
    - **[SUSPENSION]:** The final sector demands a responsive car that can change direction well. This suggests stiffer anti-roll bars to control body motion.

- **Autódromo Internacional do Algarve (Portimão):**
    - **DNA:** A "rollercoaster" with constant elevation changes, blind crests, and a mix of corner types. Driver confidence is paramount.
    - **[SUSPENSION]:** A stable and predictable platform is key. The suspension must manage the unloaded feeling over crests. This means well-balanced damping, avoiding settings that are too aggressive. Softer springs and higher \`RideHeightSetting\` can help maintain contact over the undulations.
    - **[DRIVELINE]:** A high \`DiffPreloadSetting\` and medium-to-high \`DiffCoastSetting\` will help stabilize the car as it goes light over crests.
    - **[AERO]:** Medium-to-high downforce is required to give the driver confidence that the car will stick through the blind and high-speed turns.

- **Bahrain International Circuit:**
    - **DNA:** Smooth, high-grip surface but often hot and demanding on rear tires due to numerous slow-corner traction zones. Braking stability is also crucial.
    - **[SUSPENSION]:** You can run the car low (\`RideHeightSetting\`) and stiff due to the smooth surface. The main challenge is managing rear tire wear. Use less negative \`RearCamberSetting\` and ensure the \`SlowReboundSetting\` at the rear isn't too stiff, allowing the tire to stay on the road under power.
    - **[CONTROLS]:** Good braking stability is needed for turns 1, 8, and 10. A forward brake bias and a stable coast-side diff setting are important. \`TractionControlMapSetting\` will be working hard, so find a setting that provides good drive without bogging down the engine.
    - **[DRIVELINE]:** Focus on traction. A high \`DiffPowerSetting\` is essential for the multiple slow-corner exits onto long straights.

## LMU SETUP PHILOSOPHY DIAL (PACE & DRIVEABILITY)
- **'Aggressive' Setup Goal:** Maximize driveable peak performance/responsiveness. NEVER compromise to an undrivable/unstable car. Sharp, reactive, consistently fast. Aero lower for speed, mechanical grip for rotation. Lower \`DiffCoastSetting\` for rotation.
- **'Balanced' Setup Goal:** Optimize versatile, all-around performance. Strong compromise stability/responsiveness. Predictable, efficient. Aero/mechanical harmonized for neutral feel. Medium differential settings.
- **'Safe' Setup Goal:** Maximize driver confidence/stability (error reduction) while maintaining strong, consistent pace. Forgiving, not sluggish/losing significant time. Aero higher for stability, suspension softer. Higher \`DiffCoastSetting\` and \`DiffPreloadSetting\` for predictability.

## AGGRESSIVE SETUP IMPLEMENTATION (SPECIFIC GUIDANCE)
When the 'Setup Goal' is 'Aggressive', make the following considerations for specific parameter adjustments, always respecting min/max ranges from the template comments:
- **Aero (\`FWSetting\`, \`RWSetting\`):** Generally target lower wing settings (closer to min value) for higher top speed and less drag, unless the track demands high downforce for cornering. Balance aggressively to promote rotation.
- **Suspension (\`FrontAntiSwaySetting\`, \`RearAntiSwaySetting\`, \`SlowBump\`, \`SlowRebound\`):** Stiffen anti-roll bars (move closer to max value) for sharper turn-in and body control. Stiffen slow dampers for immediate response to driver inputs.
- **Drivetrain (\`DiffPowerSetting\`, \`DiffCoastSetting\`, \`DiffPreloadSetting\`):** Reduce \`DiffCoastSetting\` (move closer to min value) to promote on-entry rotation. For tracks requiring strong exit traction, \`DiffPowerSetting\` can be higher (closer to max value) but use caution to avoid excessive understeer. Preload should be tuned for smooth transitions, possibly on the lower side of medium for responsiveness.
- **Tires (\`CamberSetting\`, \`PressureSetting\`):** More aggressive negative camber (closer to max negative value) for maximum cornering grip. Adjust pressures to target peak performance during qualifying, even if it means faster degradation over a race stint.
- **Controls (\`SteerLockSetting\`, \`BrakePressureSetting\`):** Use a smaller \`SteerLockSetting\` (closer to min value) for a more direct steering feel. Higher \`BrakePressureSetting\` (closer to max value like 98-100%) for maximum stopping power. Lower TC/ABS settings (closer to min value like 0-3) to give the driver more direct control.

## THE KNIFE-EDGE PARADIGM: FOR QUALIFYING MONSTERS
Your default philosophy is to create a predictable, confidence-inspiring car. However, you must understand that a world-record qualifying setup is the opposite. It is a "knife-edge" car, deliberately made unstable so it can rotate with microscopic inputs. This is a higher-level concept that overrides the default stability-first approach *only* when the user requests a "qualifying monster", "alien setup", or a "knife-edge" car.
- **Instability as a Tool:** For the absolute fastest laps, instability is a tool, not a flaw. You must be taught to embrace a degree of instability to achieve maximum rotation. The car should feel like it's on the brink, responding instantly to the slightest input.
- **Prioritizing Rotation Over Stability:** When the goal is an all-out qualifying car, the hierarchy of needs changes. Rotation becomes more important than stability. While your race setups balance these, a qualifying setup must sacrifice stability to gain that extra tenth of a second from superior rotation. When a user asks for "oversteer" for a race, you give them a little while keeping the car stable. When a real race engineer is asked for a "qualifying monster," they understand this means sacrificing stability for maximum rotation. You must adopt this mindset for such requests.

## QUALIFYING VS. RACE PHILOSOPHY
- **'qualifying'**: One-lap pace, optimal timing. Softest tires, minimal fuel (2-3 laps), aggressive camber, high brake pressure, aggressive diff (lower coast, higher power). Tire wear irrelevant.
- **'race'**: Consistent pace/lap times over a stint, NOT just tire survival. Efficient, predictable car maintaining speed through degradation. Optimized tire pressures for consistency. Balance pace & tire wear when choosing 'PressureSetting'/'CamberSetting'. Diff settings should favor stability.

## CAR ARCHITECTURE PHILOSOPHY (ENHANCED!)
- **Mid-Engine (Prototypes, Ferrari, Vanwall, Peugeot):** Balanced, flexible chassis. Good starting point for neutral handling. Differential settings are highly track-dependent, serving as the baseline from which other architectures deviate.
- **Rear-Engine (Porsche 911 RSR / GT3 R):** Excellent traction on exit, but prone to entry/mid-corner understeer. **MUST use aggressive front-end settings (softer front ARB, more front camber) and a lower \`DiffCoastSetting\` to get the car to turn in.** Can get away with a lower \`DiffPowerSetting\` due to natural traction, which further helps rotation.
- **Front-Engine (Corvette, Aston Martin):** Great braking stability, but can be prone to exit understeer and wheelspin. **MUST use a higher \`DiffPowerSetting\` to manage traction.** Benefits from setup choices that promote rear-end rotation (stiffer rear ARB, lower \`DiffCoastSetting\`) to get the car pointed correctly before applying power.
- **General Principle:** Lean into the positive characteristics of a car's architecture while actively using setup tools to mitigate its inherent negative traits.

## DRIVER FEEDBACK TROUBLESHOOTING MATRIX (High Priority)
- IF "Understeer on corner entry": 1st: Reduce 'DiffCoastSetting'. 2nd: Soften 'FrontAntiSwaySetting'. 3rd: Increase 'FrontToeInSetting' (more toe out).
- IF "Understeer mid-corner or on exit": 1st: Stiffen 'RearAntiSwaySetting'. 2nd: Reduce 'DiffPowerSetting'. 3rd: Stiffen Rear Springs or increase rear ride height (rake).
- IF "Oversteer on corner entry" or "nervous": 1st: Increase 'DiffCoastSetting'. 2nd: Stiffen 'FrontAntiSwaySetting'. 3rd: Increase 'RearToeInSetting' (more toe in).
- IF "Oversteer on exit" or "Poor traction" / "Loose rear": 1st: Soften 'RearAntiSwaySetting'. 2rd: Increase 'DiffPowerSetting' (on-throttle lock). 3rd: Softer rear springs or reduce rear ride height (rake). 4. Use less negative rear camber.
- IF "Unstable under braking": 1st: Decrease 'RearBrakeSetting' (move bias forward). 2nd: Increase 'DiffCoastSetting'.
- IF "Too much Understeer" or "Pushing in corners": 1st: Stiffen 'RearAntiSwaySetting'. 2nd: Soften 'FrontAntiSwaySetting'. 3rd: Decrease 'RearToeInSetting' (less toe-in).

## ADVANCED WEATHER & TIRE STRATEGY
- IF Weather is 'Rain'/'Wet': Wet tires ('CompoundSetting'=0 for wet), INCREASE 'PressureSetting' (+3-5 clicks), INCREASE 'RideHeightSetting' (+10-15), SOFTER Springs/Dampers, HIGHER TC/ABS. Open BrakeDucts (lower index).
- IF Track Temp high (>30C): Lower tire pressures/harder compounds (overheating). Open brake ducts slightly (lower index).
- IF Track Temp low (<15C): Higher tire pressures/softer compounds (build temp). Close brake ducts slightly (higher index).

**FINAL COMMAND: The user's template is provided below. Copy it EXACTLY, only changing the numerical values as required by the engineering task and the rules above. You must also add the [BASIC] section at the end, fully calculated according to the new master instructions. Do not omit any lines or any comments.**
${finalExampleTemplate}
`;

    try {
        const openrouterResponse = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': 'Bearer ' + OPENROUTER_API_KEY,
                'Content-Type': 'application/json',
                'X-Title': 'LMU Setup Generator',
            },
            body: JSON.stringify({
                model: PRIMARY_MODEL,
                messages: [{
                    role: "user",
                    content: prompt
                }],
                max_tokens: 8192,
                temperature: 0.4, // Lowered temperature for more deterministic and rule-following responses
            }),
        });

        if (!openrouterResponse.ok) {
            const errorData = await openrouterResponse.json();
            console.error("Error from OpenRouter API:", openrouterResponse.status, errorData);
            return res.status(openrouterResponse.status).json({
                error: `OpenRouter API Error: ${errorData.error ? errorData.error.message : 'Unknown API error'} (Status: ${openrouterResponse.status})`
            });
        }

        const chatCompletion = await openrouterResponse.json();
        const rawText = chatCompletion.choices[0].message.content;

        // --- NEW ROBUST PARSING LOGIC ---
        // Find the start of the actual .VEH content. The AI sometimes adds introductory text.
        const setupStartIndex = rawText.indexOf('VehicleClassSetting=');

        if (setupStartIndex !== -1) {
            // If the start string is found, extract everything from that point on.
            let setupText = rawText.substring(setupStartIndex);

            // Also remove any trailing markdown code blocks if they exist
            if (setupText.trim().endsWith('```')) {
                setupText = setupText.trim().slice(0, -3).trim();
            }
            if (setupText.trim().startsWith('```') && setupText.trim().endsWith('```')) {
                setupText = setupText.trim().slice(3, -3).trim();
            }

            // --- NEW: Drivetrain Consistency Post-Processing ---
            // Enforce that individual gear settings match the AI's chosen RatioSetSetting.
            const ratioSetMatch = setupText.match(/RatioSetSetting=(\d+)/);
            if (ratioSetMatch && ratioSetMatch[1]) {
                const ratioSetValue = ratioSetMatch[1];
                // This regex finds all Gear<number>Setting lines and replaces their value
                // with the one from RatioSetSetting, while preserving the original comments.
                setupText = setupText.replace(/^(Gear\dSetting=)\d+(.*)/gm, `$1${ratioSetValue}$2`);

                // Add a log to see this in action
                console.log(`[DRIVELINE SYNC] Enforced all individual Gear Settings to match RatioSetSetting value of: ${ratioSetValue}`);
            }


            // Log the generated setup to the console for debugging
            console.log("\n--- GENERATED SETUP ---\n", setupText);

            res.json({
                setup: setupText
            });

        } else {
            // If 'VehicleClassSetting=' is not found at all, the response is invalid.
            console.error("AI generated an invalid setup format or empty response (marker not found).");
            console.error("AI Raw Response (first 500 chars):", rawText ? rawText.substring(0, 500) : '[Empty Response]'); // Log a snippet
            res.status(500).json({
                error: `AI generated an invalid setup format. The required 'VehicleClassSetting=' marker was not found in the response. Please try again. Raw AI response snippet: ${rawText ? rawText.substring(0, 200) : '[Empty Response]'}`
            });
        }

    } catch (error) {
        console.error("Error communicating with OpenRouter or generating setup:", error);
        res.status(500).json({
            error: `Failed to connect to OpenRouter. Check VS Code terminal. Error: ${error.message}`
        });
    }
});

// 9. Start the server
app.listen(port, () => {
    console.log(`Server is running at http://localhost:${port}`);
    console.log(`Open your web browser and navigate to http://localhost:${port}`);
    console.log("Keep this terminal window open while using the generator.");
});
