// --- server.js (Final Version with Syntax Fix and Improved AI Output Directives) ---

// 1. Load environment variables from .env file
require('dotenv').config();

// 2. Import necessary libraries
const express = require('express');
const path = require('path');
// Node.js v18+ has a built-in fetch API, so node-fetch is no longer needed

// 3. Initialize Express app and define port
const app = express();
const port = process.env.PORT || 3000;

// 4. Middleware to parse JSON bodies
app.use(express.json());

// 5. Serve static files (assuming your index.html and client-side JS are in the same directory)
app.use(express.static(path.join(__dirname)));

// 6. Get your API keys from the .env file
const OPENROUTER_API_KEY = process.env.OPENROUTER_API_KEY;
// The HUGGINGFACE_API_KEY is loaded and available for use,
// but the primary setup generation uses OpenRouter as configured below.
const HUGGINGFACE_API_KEY = process.env.HUGGINGFACE_API_KEY;

// --- Validation for API Keys ---
if (!OPENROUTER_API_KEY) {
    console.error("ERROR: OPENROUTER_API_KEY not found in your .env file.");
    console.error("Please ensure you have a .env file in the same directory as server.js");
    console.error("And it contains the line: OPENROUTER_API_KEY=YOUR_ACTUAL_OPENROUTER_KEY_HERE");
    process.exit(1);
}

if (!HUGGINGFACE_API_KEY) {
    // This is a warning because the primary function uses OpenRouter.
    console.warn("WARN: HUGGINGFACE_API_KEY not found in your .env file.");
    console.warn("The application will continue, but features relying on direct Hugging Face calls will fail.");
}

// 7. Define OpenRouter API endpoint and Model
const OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions';
const PRIMARY_MODEL = 'NousResearch/Hermes-2-Pro-Llama-3-8B';

// --- Define LMU .VEH Example Templates by Category (ENHANCED with safer defaults) ---
// IMPORTANT: Each car class has ONE unique, correct, and fully flagged template.
// The [BASIC] section is intentionally ABSENT from these templates as it will be GENERATED by the AI.
const LMU_VEH_TEMPLATES = {
    'Hypercar': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(2,0,0,0) // Fixed to car's upgrade package
[GENERAL]
Notes=""
Symmetric=1
CGHeightSetting=0//Non-adjustable (Fixed)
CGRightSetting=0//Non-adjustable (Fixed)
CGRearSetting=0//Non-adjustable (Fixed)
WedgeSetting=0//N/A (Fixed)
FuelSetting=85//85L (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//Max Fuel (Fixed)
VirtualEnergySetting=72//72% (MUST BE OVERWRITTEN)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=88//N/A (Fixed)
Pitstop2Setting=88//N/A (Fixed)
Pitstop3Setting=88//N/A (Fixed)

[LEFTFENDER]
FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
FWSetting=1//Standard (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARWING]
RWSetting=3//P4 (Min: 0, Max: 9) (MUST BE OVERWRITTEN) // Hypercar RW: 0-9 (P1-P10 in game UI)

[BODYAERO]
WaterRadiatorSetting=1//25% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
OilRadiatorSetting=1//25% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
BrakeDuctSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=16//D-P1 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=10//Balanced Default (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
FrontToeInSetting=15//-0.06 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=17//0.06 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
Front3rdPackerSetting=8//0.8 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Front3rdSpringSetting=8//8 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
Front3rdTenderSpringSetting=0//Detached (Fixed)
Front3rdTenderTravelSetting=0//Detached (Fixed)
Front3rdSlowBumpSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdFastBumpSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdSlowReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Front3rdFastReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdPackerSetting=10//1.0 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Rear3rdSpringSetting=7//7 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
Rear3rdTenderSpringSetting=0//Detached (Fixed)
Rear3rdTenderTravelSetting=0//Detached (Fixed)
Rear3rdSlowBumpSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdFastBumpSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdSlowReboundSetting=0//1 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
Rear3rdFastReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ChassisAdj00Setting=0//Alternative (Fixed)
ChassisAdj01Setting=0//N/A (Fixed)
ChassisAdj02Setting=0//N/A (Fixed)
ChassisAdj03Setting=0//N/A (Fixed)
ChassisAdj04Setting=0//N/A (Fixed)
ChassisAdj05Setting=0//N/A (Fixed)
ChassisAdj06Setting=0//N/A (Fixed)
ChassisAdj07Setting=0//N/A (Fixed)
ChassisAdj08Setting=0//N/A (Fixed)
ChassisAdj09Setting=0//N/A (Fixed)
ChassisAdj10Setting=0//N/A (Fixed)
ChassisAdj11Setting=0//N/A (Fixed)

[CONTROLS]
SteerLockSetting=0//400 (16) deg (MUST BE OVERWRITTEN)
RearBrakeSetting=16//52.8:47.2 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
BrakeMigrationSetting=0//2.5% F (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakePressureSetting=80//120 kgf (100%) (MUST BE OVERWRITTEN)
HandfrontbrakePressSetting=0//0% (Fixed)
HandbrakePressSetting=0//N/A (Fixed)
TCSetting=0//Available (Fixed)
ABSSetting=0//N/A (Fixed)
TractionControlMapSetting=9//9 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCPowerCutMapSetting=8//8 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCSlipAngleMapSetting=8//8 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
AntilockBrakeSystemMapSetting=0//N/A (Fixed)

[ENGINE]
RevLimitSetting=0//8,500 (Non-adjustable) (Fixed)
EngineBoostSetting=0//N/A (Fixed)
RegenerationMapSetting=10//200kW (AI adjusts for session type: Quali=8-9, Race=10) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ElectricMotorMapSetting=3//60kW (AI adjusts for hybrid usage: 0=N/A, 1-4 for power modes) (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
EngineMixtureSetting=1//Race (Min: 0, Max: 2) (MUST BE OVERWRITTEN)
EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=0//2.98:1 (Fixed)
ReverseSetting=0//2.07 (6.18) (Fixed)
Gear1Setting=0//2.85 (~62 mph / ~100 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//2.20 (~81 mph / ~130 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//1.82 (~99 mph / ~160 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//1.56 (~118 mph / ~190 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//1.35 (~137 mph / ~220 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//1.19 (~155 mph / ~250 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Longest ratio.
Gear7Setting=0//1.05 (~174 mph / ~280 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
RatioSetSetting=0//Short (Min: 0, Max: 1 or higher based on car) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//N/A (Fixed)
DiffPowerSetting=3//25% (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
DiffCoastSetting=10//60% (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
DiffPreloadSetting=24//120 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//N/A (Fixed)
FrontDiffPowerSetting=0//10% (N/A for RWD) (Fixed)
FrontDiffCoastSetting=0//10% (N/A for RWD) (Fixed)
FrontDiffPreloadSetting=0//0 Nm (N/A for RWD) (Fixed)
RearSplitSetting=0// 0.0:100.0 (Fixed to RWD)
GearAutoUpShiftSetting=0//Off (Fixed)
GearAutoDownShiftSetting=0//Off (Fixed)

[FRONTLEFT]
CamberSetting=26//-1.4 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//135 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=5//0.5 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=10//15.95mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=9//4.9 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=26//-1.4 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=5//0.5 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=10//15.95mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=9//4.9 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=5//6 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=15//7.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=6//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=15//7.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=6//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
BrakeDiscSetting=0//4.00 cm (Fixed)
BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[BASIC]
Downforce=0.050000
Balance=0.500000
Ride=0.400000
Gearing=0.975000
Custom=1`,

    'LMP2': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(12,0,0,0) // Fixed to car's upgrade package
[GENERAL]
Notes=""
Symmetric=1
CGHeightSetting=0//Non-adjustable (Fixed)
CGRightSetting=0//Non-adjustable (Fixed)
CGRearSetting=0//Non-adjustable (Fixed)
WedgeSetting=0//N/A (Fixed)
FuelSetting=65//65L (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//N/A (Fixed)
VirtualEnergySetting=72//72% (MUST BE OVERWRITTEN)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=50//N/A (Fixed)
Pitstop2Setting=50//N/A (Fixed)
Pitstop3Setting=50//N/A (Fixed)

[LEFTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
//FWSetting=0//N/A (Fixed)

[REARWING]
RWSetting=2//P3 (Min: 0, Max: 8) (MUST BE OVERWRITTEN) // LMP2 RW: 0-8 (P1-P9 in game UI)

[BODYAERO]
WaterRadiatorSetting=2//50% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
OilRadiatorSetting=2//50% (Min: 0, Max: 4) (MUST BE OVERWRITTEN)
BrakeDuctSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=1//25% (Min: 0, Max: 3) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=9//D25 H-H (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=5//Balanced Default (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
FrontToeInSetting=13//-0.18 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=22//0.35 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
//RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
Front3rdPackerSetting=6//0.6 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
Front3rdSpringSetting=0//N/A (Fixed)
//Front3rdTenderSpringSetting=0//Detached (Fixed)
//Front3rdTenderTravelSetting=0//Detached (Fixed)
//Front3rdSlowBumpSetting=0//1 (Min: 0, Max: 10)
//Front3rdFastBumpSetting=0//1 (Min: 0, Max: 10)
//Front3rdSlowReboundSetting=0//1 (Min: 0, Max: 10)
//Front3rdFastReboundSetting=0//1 (Min: 0, Max: 10)
Rear3rdPackerSetting=7//0.7 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//Rear3rdSpringSetting=0//N/A (Fixed)
//Rear3rdTenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SlowBumpSetting=0//1 (Min: 0, Max: 10)
//FastBumpSetting=0//1 (Min: 0, Max: 10)
//SlowReboundSetting=0//1 (Min: 0, Max: 10)
//FastReboundSetting=0//1 (Min: 0, Max: 10)
//ChassisAdj00Setting=0//N/A (Fixed)

[CONTROLS]
//SteerLockSetting=3//336 (13) deg (Fixed)
RearBrakeSetting=13//54.1:45.9 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
//BrakeMigrationSetting=0// 0.0 (Fixed)
BrakePressureSetting=60//100 kgf (83%) (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
//HandfrontbrakePressSetting=0//0% (Fixed)
//HandbrakePressSetting=0//N/A (Fixed)
//TCSetting=0//Available (Fixed)
//ABSSetting=0//N/A (Fixed)
TractionControlMapSetting=7//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCPowerCutMapSetting=4//4 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
TCSlipAngleMapSetting=7//Linked (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//AntilockBrakeSystemMapSetting=0//N/A (Fixed)

[ENGINE]
//RevLimitSetting=0//8000 (Fixed)
//EngineBoostSetting=0//N/A (Fixed)
//RegenerationMapSetting=0//0% (Fixed)
ElectricMotorMapSetting=0//Not Applicable (N/A for Non-Hybrid) (Fixed)
EngineMixtureSetting=1//Race (Min: 0, Max: 1) (MUST BE OVERWRITTEN)
//EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=3//2.88:1 (Min: 0, Max: 5) (MUST BE OVERWRITTEN)
ReverseSetting=0//2.85 (8.18) (Fixed)
Gear1Setting=0//2.85 (~56 mph / ~90 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//2.20 (~71 mph / ~115 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//1.88 (~84 mph / ~135 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//1.62 (~96 mph / ~155 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//1.42 (~109 mph / ~175 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//1.27 (~121 mph / ~195 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
RatioSetSetting=1//High Speed (Min: 0, Max: 1 or higher based on car) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//N/A (Fixed)
DiffPowerSetting=0//FF6-60 deg (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
DiffCoastSetting=2//FF6-45 deg (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
DiffPreloadSetting=17//85 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//N/A (Fixed)
FrontDiffPowerSetting=0//0% (Fixed)
FrontDiffCoastSetting=0//0% (Fixed)
FrontDiffPreloadSetting=0//1 (Fixed)
RearSplitSetting=0// 0.0:100.0 (Fixed to RWD)
GearAutoUpShiftSetting=0//Off (Fixed)
GearAutoDownShiftSetting=0//Off (Fixed)

[FRONTLEFT]
CamberSetting=11//-1.5 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=3//0.3 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=5//150N/mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=10//4.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=11//-1.5 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=3//0.3 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=5//150N/mm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=10//4.5 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=4//5 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=2//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=24//7.0 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=20//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=12//1.2 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=0//1100lbf/in (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
TenderSpringSetting=0//Detached (Fixed)
TenderTravelSetting=0//Detached (Fixed)
SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=24//7.0 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=1//2 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=0//1 (soft) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[BASIC]
Downforce=0.400000
Balance=0.400000
Ride=0.400000
Gearing=0.400000
Custom=1`,

    'GTE': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(0,0,0,0)
//UpgradeClass=
//Aero package=0
//Note: settings commented out if using the default

[GENERAL]
Notes=""
Symmetric=1
//CGHeightSetting=0//Non-adjustable
//CGRightSetting=0//Non-adjustable
//CGRearSetting=0//Non-adjustable
//WedgeSetting=0//N/A
FuelSetting=33//34L (13laps)
//FuelCapacitySetting=0//+0L (0laps)
//NumPitstopsSetting=0//
//Pitstop1Setting=49//N/A
//Pitstop2Setting=49//N/A
//Pitstop3Setting=49//N/A

[LEFTFENDER]
//FenderFlareSetting=0//Standard

[RIGHTFENDER]
//FenderFlareSetting=0//Standard

[FRONTWING]
//FWSetting=0//Standard

[REARWING]
RWSetting=2//P3

[BODYAERO]
//WaterRadiatorSetting=0//No tape
//OilRadiatorSetting=0//No tape
//BrakeDuctSetting=1//33%
//BrakeDuctRearSetting=1//33%

[SUSPENSION]
//FrontWheelTrackSetting=0//Non-adjustable
//RearWheelTrackSetting=0//Non-adjustable
//FrontAntiSwaySetting=5//P5
RearAntiSwaySetting=3//Balanced Default
//FrontToeInSetting=6//-0.23 deg
//FrontToeOffsetSetting=0//N/A
RearToeInSetting=12//0.47 deg
//RearToeOffsetSetting=0//N/A
//LeftCasterSetting=0//Non-adjustable
//RightCasterSetting=0//Non-adjustable
//LeftTrackBarSetting=0//N/A
//RightTrackBarSetting=0//N/A
//Front3rdPackerSetting=0//N/A
//Front3rdSpringSetting=0//Detached
//Front3rdTenderSpringSetting=0//Detached
//Front3rdTenderTravelSetting=0//Detached
//Front3rdSlowBumpSetting=0//N/A
//Front3rdFastBumpSetting=0//N/A
//Front3rdSlowReboundSetting=0//N/A
//Front3rdFastReboundSetting=0//N/A
//Rear3rdPackerSetting=0//N/A
//Rear3rdSpringSetting=0//Detached
//Rear3rdTenderSpringSetting=0//Detached
//Rear3rdTenderTravelSetting=0//Detached
//Rear3rdSlowBumpSetting=0//N/A
//Rear3rdFastBumpSetting=0//N/A
//Rear3rdSlowReboundSetting=0//N/A
//Rear3rdFastReboundSetting=0//N/A
//ChassisAdj00Setting=0//N/A
//ChassisAdj01Setting=0//N/A
//ChassisAdj02Setting=0//N/A
//ChassisAdj03Setting=0//N/A
//ChassisAdj04Setting=0//N/A
//ChassisAdj05Setting=0//N/A
//ChassisAdj06Setting=0//N/A
//ChassisAdj07Setting=0//N/A
//ChassisAdj08Setting=0//N/A
//ChassisAdj09Setting=0//N/A
//ChassisAdj10Setting=0//N/A
//ChassisAdj11Setting=0//N/A

[CONTROLS]
//SteerLockSetting=6//540 (18) deg
RearBrakeSetting=17//52.8:47.2
//BrakeMigrationSetting=0// 0.0
//BrakePressureSetting=40//80 kgf (100%)
//HandfrontbrakePressSetting=0//N/A
//HandbrakePressSetting=0//N/A
//TCSetting=0//Available
//ABSSetting=0//N/A
TractionControlMapSetting=6//6
TCPowerCutMapSetting=2//2
//TCSlipAngleMapSetting=4//4
//AntilockBrakeSystemMapSetting=0//N/A

[ENGINE]
//RevLimitSetting=0//7,400
//EngineBoostSetting=0//N/A
//RegenerationMapSetting=0//0%
//ElectricMotorMapSetting=0//
EngineMixtureSetting=1//Race lean
//EngineBrakingMapSetting=0//N/A

[DRIVELINE]
//FinalDriveSetting=0//3.664
//ReverseSetting=0//3.083
Gear1Setting=0//2.067
Gear2Setting=0//1.706
Gear3Setting=0//1.368
Gear4Setting=0//1.143
Gear5Setting=0//1.000
Gear6Setting=0//0.889
//RatioSetSetting=0//Standard
//DiffPumpSetting=0//N/A
//DiffPowerSetting=0//Non-adjustable
//DiffCoastSetting=0//Non-adjustable
DiffPreloadSetting=18//90 Nm
//FrontDiffPumpSetting=0//0%
//FrontDiffPowerSetting=0//0%
//FrontDiffCoastSetting=0//0%
//FrontDiffPreloadSetting=0//1
//RearSplitSetting=0//RWD
//GearAutoUpShiftSetting=0//Off
//GearAutoDownShiftSetting=0//Off

[FRONTLEFT]
CamberSetting=28//-2.2 deg
//PressureSetting=0//140 kPa
//PackerSetting=20//2.0 cm
SpringSetting=5//220 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=0//5.0 cm
SlowBumpSetting=8//8
FastBumpSetting=10//10
SlowReboundSetting=10//10
FastReboundSetting=10//10
//BrakeDiscSetting=0//3.56 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//

[FRONTRIGHT]
CamberSetting=28//-2.2 deg
//PressureSetting=0//140 kPa
//PackerSetting=20//2.0 cm
SpringSetting=5//220 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=0//5.0 cm
SlowBumpSetting=8//8
FastBumpSetting=10//10
SlowReboundSetting=10//10
FastReboundSetting=10//10
//BrakeDiscSetting=0//3.56 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//

[REARLEFT]
CamberSetting=33//-1.2 deg
//PressureSetting=0//140 kPa
PackerSetting=25//2.5 cm
SpringSetting=1//140 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=22//7.2 cm
SlowBumpSetting=7//7
FastBumpSetting=7//7
SlowReboundSetting=7//7
FastReboundSetting=7//7
//BrakeDiscSetting=0//3.20 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//

[REARRIGHT]
CamberSetting=33//-1.2 deg
//PressureSetting=0//140 kPa
PackerSetting=25//2.5 cm
SpringSetting=1//140 N/mm
//TenderSpringSetting=0//Detached
//TenderTravelSetting=0//Detached
//SpringRubberSetting=0//Detached
RideHeightSetting=22//7.2 cm
SlowBumpSetting=7//7
FastBumpSetting=7//7
SlowReboundSetting=7//7
FastReboundSetting=7//7
//BrakeDiscSetting=0//3.20 cm
//BrakePadSetting=0//1
//CompoundSetting=0//Soft
//EquippedTireIDSetting=0//

[BASIC]
Downforce=0.500000
Balance=0.500000
Ride=0.500000
Gearing=0.500000
Custom=1`,

    'GT3': `VehicleClassSetting="[[CAR_NAME]]"
UpgradeSetting=(3276,0,0,0) // Fixed to car's upgrade package
[GENERAL]
Notes=""
Symmetric=1
//CGHeightSetting=0//Non-adjustable (Fixed)
//CGRightSetting=0//Non-adjustable (Fixed)
//CGRearSetting=0//Non-adjustable (Fixed)
//WedgeSetting=0//N/A (Fixed)
FuelSetting=92//0.93 (MUST BE OVERWRITTEN)
FuelCapacitySetting=0//93.0l (22.5 laps) (Fixed)
VirtualEnergySetting=100//100% (22.0 laps) (Fixed)
NumPitstopsSetting=0//N/A (Fixed)
Pitstop1Setting=59//N/A (Fixed)
Pitstop2Setting=59//N/A (Fixed)
Pitstop3Setting=59//N/A (Fixed)

[LEFTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[RIGHTFENDER]
//FenderFlareSetting=0//N/A (Fixed)

[FRONTWING]
//FWSetting=0//N/A (Fixed)

[REARWING]
RWSetting=2//P3 (Min: 0, Max: 14) (MUST BE OVERWRITTEN) // GT3 RW: 0-14 (P1-P15 in game UI)

[BODYAERO]
WaterRadiatorSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
OilRadiatorSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctSetting=3//60mm (Min: 0, Max: 3) (MUST BE OVERWRITTEN)
BrakeDuctRearSetting=2//40mm (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[SUSPENSION]
FrontWheelTrackSetting=0//Non-adjustable (Fixed)
RearWheelTrackSetting=0//Non-adjustable (Fixed)
FrontAntiSwaySetting=7//P7 (dur) (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
RearAntiSwaySetting=4//P4 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FrontToeInSetting=7//-0.117 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
FrontToeOffsetSetting=0//N/A (Fixed)
RearToeInSetting=8//0 deg (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
RearToeOffsetSetting=0//N/A (Fixed)
LeftCasterSetting=0//Non-adjustable (Fixed)
RightCasterSetting=0//Non-adjustable (Fixed)
LeftTrackBarSetting=0//N/A (Fixed)
RightTrackBarSetting=0//N/A (Fixed)
//Front3rdPackerSetting=0//N/A (Fixed)
//Front3rdSpringSetting=0//N/A (Fixed)
//Front3rdTenderSpringSetting=0//Détaché (Fixed)
//Front3rdTenderTravelSetting=0//Détaché (Fixed)
//Front3rdSlowBumpSetting=0//N/A (Fixed)
//Front3rdFastBumpSetting=0//N/A (Fixed)
//Front3rdSlowReboundSetting=0//N/A (Fixed)
//Front3rdFastReboundSetting=0//N/A (Fixed)
//Rear3rdPackerSetting=0//N/A (Fixed)
//Rear3rdSpringSetting=0//N/A (Fixed)
//Rear3rdTenderSpringSetting=0//Détaché (Fixed)
//Rear3rdTenderTravelSetting=0//Détaché (Fixed)
//Rear3rdSlowBumpSetting=0//N/A (Fixed)
//FastBumpSetting=0//N/A (Fixed)
//SlowReboundSetting=0//N/A (Fixed)
//FastReboundSetting=0//N/A (Fixed)

[CONTROLS]
SteerLockSetting=4//380° (11.2°) (Min: 0, Max: 15) (MUST BE OVERWRITTEN)
RearBrakeSetting=21//51.8:48.2 (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
//BrakeMigrationSetting=0// 0.0 (Fixed)
//BrakePressureSetting=80//120 kgf (100%) (Fixed)
//HandfrontbrakePressSetting=0//N/A (Fixed)
//HandbrakePressSetting=0//N/A (Fixed)
//TCSetting=0//Disponible (Fixed)
//ABSSetting=0//Disponible (Fixed)
//TractionControlMapSetting=8//8 (Fixed)
TCPowerCutMapSetting=3//3 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//TCSlipAngleMapSetting=10//10 (Fixed)
AntilockBrakeSystemMapSetting=11//11 (Min: 0, Max: 15) (MUST BE OVERWRITTEN)

[ENGINE]
//RevLimitSetting=0//9,400 (Fixed)
//EngineBoostSetting=0//N/A (Fixed)
//RegenerationMapSetting=0//0% (Fixed)
ElectricMotorMapSetting=0//Not Applicable (N/A for Non-Hybrid) (Fixed)
//EngineMixtureSetting=1//Race (Fixed)
//EngineBrakingMapSetting=0//N/A (Fixed)

[DRIVELINE]
FinalDriveSetting=0//Fixed (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
ReverseSetting=0//Fixed
Gear1Setting=0//Fixed (~95 km/h / ~59 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear2Setting=0//Fixed (~130 km/h / ~81 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear3Setting=0//Fixed (~160 km/h / ~99 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear4Setting=0//Fixed (~190 km/h / ~118 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear5Setting=0//Fixed (~220 km/h / ~137 mph) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Shortest ratio, 1=Longest ratio.
Gear6Setting=0//Fixed (~250 km/h / ~155 km/h) (Min: 0, Max: 1) (MUST BE OVERWRITTEN) // LMU specific: 0=Longest ratio.
RatioSetSetting=0//Short (Min: 0, Max: 1) (MUST BE OVERWRITTEN)
DiffPumpSetting=0//Non-adjustable (Fixed)
DiffPowerSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
DiffCoastSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
DiffPreloadSetting=28//78 Nm (Min: 0, Max: 100) (MUST BE OVERWRITTEN)
FrontDiffPumpSetting=0//0% (Fixed)
FrontDiffPowerSetting=0//0% (Fixed)
FrontDiffCoastSetting=0//0% (Fixed)
FrontDiffPreloadSetting=0//1 (Fixed)
RearSplitSetting=0//RWD (Fixed)
GearAutoUpShiftSetting=0//Non (Fixed)
GearAutoDownShiftSetting=0//Non (Fixed)

[FRONTLEFT]
CamberSetting=26//-1.80 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=9//0.9 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=3//4 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Standard (Fixed)
//SpringRubberSetting=0//N/A (Fixed)
//RideHeightSetting=0//5.0 cm (MUST BE OVERWRITTEN)
SlowBumpSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//12 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.56 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[FRONTRIGHT]
CamberSetting=26//-1.80 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=9//0.9 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=3//4 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Standard (Fixed)
//SpringRubberSetting=0//N/A (Fixed)
//RideHeightSetting=0//5.0 cm (MUST BE OVERWRITTEN)
SlowBumpSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=6//12 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.56 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARLEFT]
CamberSetting=25//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=14//1.4 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=1//2 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Standard (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=16//6.6 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=7//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
//CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[REARRIGHT]
CamberSetting=25//-1.40 deg (Min: 0, Max: 40) (MUST BE OVERWRITTEN)
PressureSetting=5//140 kPa (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
PackerSetting=14//1.4 cm (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
SpringSetting=1//2 (Min: 0, Max: 20) (MUST BE OVERWRITTEN)
//TenderSpringSetting=0//Detached (Fixed)
//TenderTravelSetting=0//Detached (Fixed)
//SpringRubberSetting=0//Detached (Fixed)
RideHeightSetting=16//6.6 cm (Min: 0, Max: 30) (MUST BE OVERWRITTEN)
SlowBumpSetting=7//11 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastBumpSetting=4//14 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
SlowReboundSetting=11//7 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
FastReboundSetting=2//16 (Min: 0, Max: 10) (MUST BE OVERWRITTEN)
//BrakeDiscSetting=0//3.20 cm (Fixed)
//BrakePadSetting=0//1 (Fixed)
CompoundSetting=0//Medium (Min: 0, Max: 2) (MUST BE OVERWRITTEN)

[BASIC]
Downforce=0.400000
Balance=0.400000
Ride=0.400000
Gearing=0.400000
Custom=1`
};

// 8. Define a route for AI setup requests
app.post('/generate-setup', async (req, res) => {
    // Safely destructure all possible values from the request body
    const {
        car, track, request, selectedCarCategory,
        selectedCarDisplay, selectedTrackDisplay, setupGoal,
        sessionGoal, selectedWeather, trackTemp, specificRequest, driverFeedback
    } = req.body;

    // Validate essential parameters
    if (!car || !track || !setupGoal || !selectedCarCategory) {
        return res.status(400).json({
            error: "Please provide Car, Track, Setup Goal, and Car Category details."
        });
    }

    // Handle potential category key mismatch
    let finalCategory = selectedCarCategory;
    if (selectedCarCategory === 'LMGT3' && LMU_VEH_TEMPLATES['GT3']) {
        finalCategory = 'GT3';
    } else if (selectedCarCategory === 'GT3' && !LMU_VEH_TEMPLATES['GT3']) { // Check if 'GT3' is missing
        finalCategory = 'GTE'; // Fallback if needed, or handle error
    }

    let exampleTemplate = LMU_VEH_TEMPLATES[finalCategory];
    if (!exampleTemplate) {
        return res.status(400).json({
            error: `No .VEH template found for car category: ${finalCategory}. Ensure selected car has a valid category.`
        });
    }

    // --- CRITICAL: LE MANS SPECIFIC OVERRIDE LOGIC (Server-Side Enforcement) ---
    // This ensures Le Mans gets the absolute lowest drag settings regardless of AI's broader interpretation.
    let finalExampleTemplate = exampleTemplate; // Start with the chosen template

    const trackOverrides = (trackName, template) => {
        let overriddenTemplate = template;
        // Generic regex to replace a setting's number while preserving its trailing comment
        const replaceSetting = (settingName, newValue, regexFlags = 'm') => {
            const regex = new RegExp(`^(${settingName}=)\\d+(.*)`, regexFlags);
            overriddenTemplate = overriddenTemplate.replace(regex, `$1${newValue}$2`);
        };

        const replaceSectionSetting = (section, settingName, newValue, regexFlags = 'm') => {
            const regex = new RegExp(`^(${section}[\\s\\S]*?${settingName}=)\\d+(.*)`, regexFlags);
             overriddenTemplate = overriddenTemplate.replace(regex, `$1${newValue}$2`);
        };


        if (trackName === "Circuit de la Sarthe (Le Mans)" || trackName === "Autodromo Nazionale Monza") {
            const minAeroSetting = 0;
            const note = trackName === "Circuit de la Sarthe (Le Mans)" ?
                'Notes="Le Mans override applied: Absolute minimum drag prioritized. All aero, ride height, and radiators minimized for top speed. Gearing set to longest possible configuration."' :
                'Notes="Monza override applied: Absolute minimum drag prioritized. All aero, ride height, and radiators minimized for top speed. Gearing set to longest possible configuration."';
            
            replaceSectionSetting('\\[FRONTWING\\]', 'FWSetting', minAeroSetting);
            replaceSectionSetting('\\[REARWING\\]', 'RWSetting', minAeroSetting);

            let maxFinalDrive;
            if (finalCategory === 'Hypercar') maxFinalDrive = 7;
            else if (finalCategory === 'LMP2') maxFinalDrive = 5;
            else if (finalCategory === 'GT3' || finalCategory === 'GTE') maxFinalDrive = 10;
            
            replaceSectionSetting('\\[DRIVELINE\\]', 'FinalDriveSetting', maxFinalDrive);
            overriddenTemplate = overriddenTemplate.replace(/^(Gear\dSetting=)\d+(.*)/gm, `$11$2`);
            replaceSetting('RatioSetSetting', 1);

            replaceSetting('WaterRadiatorSetting', 0);
            replaceSetting('OilRadiatorSetting', 0);
            replaceSetting('BrakeDuctSetting', 0);
            replaceSetting('BrakeDuctRearSetting', 0);

            overriddenTemplate = overriddenTemplate.replace(/^(RideHeightSetting=)\d+(.*)/gm, `$10$2`);
            overriddenTemplate = overriddenTemplate.replace(/Notes=""/, note);

        } else if (trackName === "Sebring International Raceway") {
            const note = 'Notes="Sebring override applied: Prioritized maximum bump absorption. Dampers and Anti-Roll Bars set to softest. Ride height increased to absorb bumps."';
            
            // Set dampers and ARBs to very soft values (e.g., 0 or 1)
            replaceSetting('Front3rdSlowBumpSetting', 0);
            replaceSetting('Front3rdFastBumpSetting', 0);
            replaceSetting('Front3rdSlowReboundSetting', 0);
            replaceSetting('Front3rdFastReboundSetting', 0);
            replaceSetting('Rear3rdSlowBumpSetting', 0);
            replaceSetting('Rear3rdFastBumpSetting', 0);
            replaceSetting('Rear3rdSlowReboundSetting', 0);
            replaceSetting('Rear3rdFastReboundSetting', 0);
            
            replaceSetting('FrontAntiSwaySetting', 1);
            replaceSetting('RearAntiSwaySetting', 1);

            // Set ride heights high
            overriddenTemplate = overriddenTemplate.replace(/^(RideHeightSetting=)\d+(.*)/gm, `$120$2`);
            overriddenTemplate = overriddenTemplate.replace(/Notes=""/, note);
        }
        return overriddenTemplate;
    };

    finalExampleTemplate = trackOverrides(track, finalExampleTemplate);

    // UPGRADE: Dynamically insert the user's selected car name into the template
    finalExampleTemplate = finalExampleTemplate.replace('[[CAR_NAME]]', car);


    const sessionDuration = req.body.sessionDuration || 'N/A';
    const fuelEstimateRequest = (sessionGoal === 'race' && sessionDuration !== 'N/A' && !isNaN(parseInt(sessionDuration))) ?
        `Estimate fuel for a ${sessionDuration} minute race.` : '';
    const weatherGuidance = `Current weather is ${selectedWeather}.`;
    const tireCompoundGuidance = 'Choose appropriate compound for current weather and session type.';


    // =====================================================================================
    // --- AI PROMPT --- THIS IS THE CRITICAL SECTION THAT HAS BEEN IMPROVED ---
    // =====================================================================================
    const prompt = `
You are a world-class LMU race engineer. Your task is to take the user's request and the provided .VEH template, and output a complete, physically realistic, and numerically valid .VEH setup file.

**ULTRA-CRITICAL FORMATTING INSTRUCTIONS - FAILURE TO FOLLOW THESE IS A TASK FAILURE:**
1.  You will be given a complete .VEH file template below.
2.  You MUST output the ENTIRE file, modified with your new values.
3.  You MUST PRESERVE THE ORIGINAL COMMENTS (the text starting with //) on every line that has one.
4.  Your ONLY job is to change the **NUMBER** before the comment. DO NOT delete or alter the comments.

---
**EXAMPLE OF PERFECT EXECUTION:**

**IF the template line is this:**
RWSetting=3//P4 (Min: 0, Max: 9) (MUST BE OVERWRITTEN) // Hypercar RW: 0-9 (P1-P10 in game UI)

**And you decide the correct value is 8, YOUR correct output for that line is:**
RWSetting=8//P4 (Min: 0, Max: 9) (MUST BE OVERWRITTEN) // Hypercar RW: 0-9 (P1-P10 in game UI)

You will do this for the entire file. Any other format is a failure.
---

## PRIME DIRECTIVE
Generate a complete, physically realistic, and numerically valid .VEH setup. Replace placeholders with calculated, logical numbers. '0' for adjustable settings is a failure.

## PERSONA & PHILOSOPHY
You are a world-class LMU race engineer. Your core philosophy is to prioritize a stable, predictable platform that inspires driver confidence, not one that is simply fast on paper. You understand that every setup change is a trade-off. Your goal is to generate predictable, realistic setups, perfectly suited to the driver's request and feedback. You MUST explain your key decisions in the '[GENERAL] Notes' section.

## CRITICAL INSTRUCTION
Populate '[GENERAL] Notes' with a concise engineering debrief. If a track-specific override (e.g., Le Mans aero) was applied, explicitly state it and explain how it overrides general setup philosophies. For your most important adjustments, explain the engineering reason for the specific parameter changes (e.g., 'Increased RearCamberSetting to reduce oversteer on exit', 'Softened front fast dampers for better bump absorption at Sebring').

## THOUGHT PROCESS & HIERARCHY
1.  **Session Type (Qualifying vs. Race):** Dictates overall setup philosophy.
2.  **Driver Feedback is KING:** Address 'Driver Problem to Solve' first. Consult 'DRIVER FEEDBACK TROUBLESHOOTING MATRIX' and the new 'DRIVER REQUEST INTERPRETATION GUIDE'. Apply Primary/Secondary solutions. All other decisions must align with solving the driver's issue.
3.  **Track DNA & Weather:** Analyze the track's unique demands ('TRACK DNA DATABASE') and weather conditions ('ADVANCED WEATHER & TIRE STRATEGY'). Apply baseline decisions and mention any necessary compromises in your notes.
4.  **Car Architecture:** Apply specific adjustments based on the car's inherent traits ('CAR ARCHITECTURE PHILOSOPHY').
5.  **Overall Setup Goal:** Use the driver's 'Setup Goal' ('Safe', 'Balanced', 'Aggressive') from the 'LMU SETUP PHILOSOPHY DIAL' to fine-tune all settings.
5.5. **Generate [BASIC] Parameters (MANDATORY AND CRITICAL):** You MUST dynamically calculate and GENERATE the [BASIC] section at the end of the .VEH file. This section is NOT in the template you are given; it must be fully derived from your setup choices and reflect the overall setup goal and track characteristics.
    - Every parameter ('Downforce', 'Balance', 'Ride', 'Gearing') MUST be a **uniquely calculated float (e.g., 0.125000)**.
    - **Outputting a generic default like 0.500000 is a critical failure, UNLESS your calculation genuinely results in that optimal value.**
    - **'Downforce'**: Represents overall aero grip. Low-drag setups (Le Mans, Monza) should be low (0.05-0.15). High-downforce tracks (Portimão) should be high (0.65-0.95). Balanced tracks get the middle range (0.25-0.45).
    - **'Balance'**: Represents understeer/oversteer. Aggressive oversteer setups are low (0.15-0.35). Neutral is mid-range (0.45-0.55). Stable understeer setups are high (0.65-0.85). Adjust according to driver request and track needs.
    - **'Ride'**: Represents suspension compliance. Stiff and low for smooth tracks (0.075-0.25). Compliant and high for bumpy tracks like Sebring (0.75-0.925). Mid-range for others (0.35-0.65).
    - **'Gearing'**: Represents the trade-off between acceleration and top speed. Long gearing for top speed tracks is high (0.85-0.975). Short gearing for acceleration tracks is low (0.075-0.25). Mid-range for balanced tracks (0.25-0.85). This MUST correspond to your detailed gear ratio selections.
    - **'Custom'**: Must always be 1.
6.  **Engineer's Debrief:** Write your concise summary in the 'Notes' section as per the 'CRITICAL INSTRUCTION'.

// =====================================================================================
// --- START OF NEW MASTER KNOWLEDGE BASE ---
// =====================================================================================

## LMU SETUP FUNDAMENTALS (DEEP DIVE)
- **The Platform Concept:** The car's chassis is a 'platform'. All setup changes aim to keep this platform stable and predictable. A stable platform allows the aerodynamics to work efficiently and gives the driver confidence. Key elements are pitch (braking/acceleration), roll (cornering), and heave (vertical movement over bumps). Your goal is to control these motions.
- **Pyramid of Grip:** Grip starts at the tires. 1. **Tires:** Must be kept in their optimal temperature and pressure window with the largest possible contact patch on the road. 2. **Suspension:** Manages the tire's contact with the road. It controls weight transfer and absorbs bumps. 3. **Aerodynamics:** Pushes the car onto the track, generating huge amounts of grip at speed. Aero is useless if the suspension can't keep the tires on the asphalt. All setup decisions must respect this hierarchy.
- **The Law of Trade-Offs:** Every single change you make has a consequence. More rear wing gives more cornering grip but reduces top speed. Softer springs absorb bumps better but make the car less responsive. Your job is to find the best compromise for the specific car, track, and driver.

## ADVANCED AERODYNAMIC PRINCIPLES
- **Aero Balance & Center of Pressure (CoP):** This is the point where the total aerodynamic force acts on the car. It's like the car's center of gravity, but for air pressure. Moving the CoP forward (e.g., more front wing) increases front-end grip (more oversteer). Moving it rearward (e.g., more rear wing) increases rear-end grip (more understeer).
- **Rake:** This is the angle of the car's floor relative to the ground, created by running the rear ride height higher than the front. A positive rake (rear higher than front) increases the expansion of air under the car, creating a low-pressure area that sucks the car to the ground (downforce from the floor/diffuser).
  - **Effect of Rake:** More rake generally increases overall downforce and shifts the aero balance forward. However, too much rake can "stall" the diffuser, causing a sudden loss of rear downforce. It's a powerful but sensitive tool.
- **Aero Platform Sensitivity:** Downforce is highly sensitive to ride height. As the car gets closer to the ground, the underbody aerodynamics work much more effectively. However, if the car runs too low, it can bottom out, which instantly breaks the airflow and causes a sudden loss of grip. This is why stiff springs are required on high-downforce, high-speed tracks to prevent the car's ride height from changing too much.

## SUSPENSION GEOMETRY & DAMPING DEEP DIVE
- **Camber Explained:** Negative camber is when the top of the tire is tilted inward. In a corner, the car rolls, and this negative camber helps to keep the outside tire's contact patch flat on the road, maximizing grip.
  - **Trade-off:** Too much negative camber reduces the tire's contact patch during straight-line braking and acceleration. The goal is to use just enough camber for cornering grip without sacrificing too much straight-line performance.
- **Toe Explained:**
  - **Front Toe:** Toe-out (negative values) means the front of the tires point away from each other. This makes the car eager to turn-in but can cause instability on the straights. Toe-in (positive values) improves straight-line stability but can make the car reluctant to initiate a turn.
  - **Rear Toe:** Rear toe-in is CRITICAL for stability. It means the front of the rear tires point towards the centerline of the car. This provides significant stability under braking and on-throttle at corner exit. Nearly all race setups use some amount of rear toe-in. Rear toe-out is almost never used as it makes the car extremely unstable.
- **Anti-Roll Bars (ARBs) Explained:** The ARB is a bar that connects the left and right wheels on an axle. Its job is to control how much the car's body rolls during cornering.
  - **Stiffening the front ARB** resists roll at the front, transferring more load to the outside front tire. This reduces front-end grip and increases understeer.
  - **Stiffening the rear ARB** resists roll at the rear, transferring more load to the outside rear tire. This reduces rear-end grip and increases oversteer. ARBs are your primary tool for adjusting mid-corner balance.
- **Dampers Explained:** Dampers (or shock absorbers) control the *speed* of the suspension's movement. They are critical for managing the platform and keeping the tires on the road.
  - **Bump:** Controls the suspension compressing.
    - **Slow-Speed Bump:** Manages the slow movements of the car's body, like roll during cornering and pitch during braking/acceleration. A stiffer slow bump setting provides more support and responsiveness.
    - **Fast-Speed Bump:** Manages the fast movements from hitting bumps and curbs. A softer fast bump setting is needed to absorb these impacts without throwing the car off balance.
  - **Rebound:** Controls the suspension extending back out.
    - **Slow-Speed Rebound:** Manages the body's return after a slow movement. It's crucial for controlling how the car "takes a set" in a corner.
    - **Fast-Speed Rebound:** Controls the wheel returning to the road after hitting a bump. It must be set correctly to keep the tire in contact with the ground.
  - **Relationship:** Dampers must work in harmony with the springs. A very stiff spring needs strong rebound damping to control it, otherwise the car will oscillate.

## DIFFERENTIAL DEEP DIVE (ADVANCED)
- The differential allows the outside wheel to rotate faster than the inside wheel in a corner. Tuning it controls how much it "locks" the two wheels together. This is a primary tool for managing stability and rotation. Your settings here MUST be based on the car and track.
- **Power (Acceleration) Lock - \`DiffPowerSetting\`:** Controls locking on-throttle.
  - **More Lock (Higher Value):** Forces rear wheels to rotate at a similar speed. Improves traction on corner exit, preventing inside wheelspin. **CRITICAL FOR:**
    - **Traction-Limited Tracks:** Use higher values for tracks with slow, hard acceleration zones (e.g., **Sebring, Portimão**).
    - **Front-Engine Cars (Corvette, Aston):** These cars are traction-limited on exit. MUST use higher power lock to prevent wheelspin.
    - **'Safe'/'Stable' Setups:** Higher lock provides a predictable throttle response and prevents snap-oversteer on exit.
  - **Less Lock (Lower Value):** Allows wheels to rotate at different speeds. Helps the car rotate on-throttle but can cause inside wheelspin. **USEFUL FOR:**
    - **High-Speed Tracks:** On tracks like **Monza or Le Mans**, corner exit is less about raw traction and more about smooth momentum. A lower lock helps the car turn without scrubbing speed.
    - **Rear-Engine Cars (Porsche):** These have natural traction. They can use less power lock, which helps mitigate their inherent understeer.
    - **'Aggressive' Setups:** Lower lock allows a skilled driver to use the throttle to help steer the car.

- **Coast (Deceleration) Lock - \`DiffCoastSetting\`:** Controls locking off-throttle (braking/turn-in).
  - **More Lock (Higher Value):** Provides significant stability on corner entry by locking the rear axle. **CRITICAL FOR:**
    - **High-Speed Stability:** Essential for tracks with fast, challenging entries (e.g., **Le Mans Porsche Curves, Monza chicanes, Spa Pouhon**). Prevents the rear from becoming light and loose.
    - **'Safe'/'Stable' Setups:** This is a primary tool for confidence on corner entry.
  - **Less Lock (Lower Value):** Allows the rear wheels to rotate freely, helping the car point into the corner and reducing entry understeer. **USEFUL FOR:**
    - **Technical Tracks:** Helpful for tight, low-speed corners where rotation is key (e.g., **Fuji Sector 3, Sebring T7/T10**).
    - **'Aggressive' Setups:** The main tool for achieving a "pointy" car that turns in sharply. If too low, the car will be very nervous on entry ('lift-off oversteer').

- **Preload (\`DiffPreloadSetting\`):** A static amount of lock always present. It determines the breakaway force required before the power/coast settings engage and smooths the transition between them.
  - **Higher Preload:** Increases overall stability and predictability. The differential feels less "active". **CRITICAL FOR:**
    - **Bumpy Tracks (Sebring):** Prevents the differential from locking/unlocking erratically as tires momentarily lose contact with the ground. This is a key to compliance and driver confidence.
    - **'Safe'/'Stable' Setups:** Makes the car's reactions to throttle/brake inputs smoother and more benign.
  - **Lower Preload:** Makes the transition between power and coast settings more aggressive and noticeable. Can improve initial turn-in but may make the car feel "snappy". Generally reserved for expert drivers on smooth tracks who want maximum responsiveness.

// =====================================================================================
// --- END OF NEW MASTER KNOWLEDGE BASE ---
// =====================================================================================


## DRIVER REQUEST INTERPRETATION GUIDE (NEW!)
- IF the driver asks for "oversteer", "rotation", or a "pointy" car, their goal is NOT an unstable car. You must interpret this as a request for an AGGRESSIVE setup philosophy. The car must turn in sharply but remain PREDICTABLE and CONTROLLABLE on throttle exit. It should feel 'on the edge' but never 'over the edge'.
- IF the driver asks for "understeer", "stability", or a "safe" car, you must interpret this as a request for a SAFE setup philosophy. The car should be forgiving and inspire confidence, even if it sacrifices some ultimate rotation speed.
- In all cases, a setup that is "so oversteery it's undrivable" is a COMPLETE FAILURE. The ultimate goal is always a drivable car that fits the driver's preference on the spectrum from Safe to Aggressive.

## REAR PLATFORM STABILITY (MANDATORY PHILOSOPHY - REFINED!)
- The rear of the car MUST be predictable. A "loose" or "snappy" rear end is a failed setup, regardless of the user's request for "oversteer".
- Your goal is to create a rear end that rotates willingly but is always predictable and communicative. You must achieve this with a balanced combination of rear toe, damping, and differential settings.
- **AVOID** setting Anti-Roll Bars (FrontAntiSwaySetting, RearAntiSwaySetting) to 0, which detaches them. A detached bar often creates an unpredictable platform. Always start from a connected, functional baseline.
- **Rear Toe:** ALWAYS use a significant amount of Rear Toe-In for stability. For most cars and tracks, a value between 18 and 24 is a safe and effective starting point. NEVER use rear toe-out.
- **Differential Power Lock:** To prevent corner exit wheelspin and a loose rear, use a relatively HIGH 'DiffPowerSetting'. A higher value locks the differential more on-throttle, forcing both wheels to turn together and providing better traction. Start with higher values (e.g., 10-14 for Hypercar) and only reduce if the car has too much understeer on exit.
- **Rear Anti-Roll Bar:** Err on the side of a SOFTER rear anti-roll bar ('RearAntiSwaySetting'). A stiff rear ARB is a primary cause of snap oversteer. It is better to have a slightly softer rear and use other tools to manage rotation.
- **Summary:** Prioritize Rear Toe-In and a locked Diff Power setting as your primary tools for creating a stable but rotatable car. Avoid an overly stiff rear anti-roll bar.

## LMU GAME MECHANICS & NUANCES
- Tuning MUST be LMU simulation-based.

### LMU Gearing Index Behavior
- Individual gears ('Gear1Setting' to 'Gear7Setting'): **INVERSE relationship**.
    - LOWER index (0) = SHORTEST ratio.
    - HIGHER index (1) = LONGEST ratio.
- **Range Limit**: Individual gears LIMITED TO ONLY INDICES 0 AND 1.
- 'FinalDriveSetting': HIGHER index = longer overall gearing.
- Apply LMU-specific gearing logic.

### Other Nuances
- 'FuelSetting', 'VirtualEnergySetting', 'NumPitstopsSetting' adjust.
- UpgradeSetting values fixed.

## LMU PHYSICS & TUNING REFERENCE
- **Aero**: Wings ('FWSetting'/'RWSetting'): Grip vs. drag. Ducts: temp/drag. **Maximizing straight-line speed requires absolute minimal drag (low wings, closed ducts, low ride height). High downforce generates drag but provides cornering grip.**
- **Suspension**: Springs ('PackerSetting'/'SpringSetting') control ride height/stiffness. Dampers ('Slow Bump'/'Fast Bump', 'Slow Rebound'/'Fast Rebound') control movement. 'AntiSwaySetting' (ARB) controls body roll/load. 'CamberSetting' controls tire angle. 'ToeInSetting' controls tire angle. 'RideHeightSetting' impacts drag/CG. Packers limit travel. **Effective vertical load management and maximum tire contact are crucial.**
- **Drivetrain**: 'FinalDriveSetting' overall gear ratio. Individual gears fine-tune. Differential ('DiffPowerSetting', 'DiffCoastSetting', 'DiffPreloadSetting') controls power. **Gearing ratio choice directly impacts acceleration vs. top speed across different speed ranges.**
- **Brakes**: 'RearBrakeSetting' (Bias), 'BrakePressureSetting', 'AntilockBrakeSystemMapSetting' (ABS), 'TractionControlMapSetting' (TC) control braking/traction.

### Tires
- 'PressureSetting': (Min: 0/~130 kPa, Max: 10/~170 kPa). **Goal: Optimal operating temperature/pressure window.**
- 'CompoundSetting': **LMU specific compound availability:**
    - Hypercar/GTE: 0=Wet, 1=Soft, 2=Medium, 3=Hard.
    - LMP2/GT3: ONLY 0=Wet, 1=Medium. (Soft/Hard NOT available).
    - MUST select available compound.

### Aero
- 'FWSetting'/'RWSetting' indices: (0=low, higher=more downforce).
    - **Hypercar FW**: Min: 0, Max: 2. **RW**: Min: 0, Max: 9 (P1-P10).
    - **LMP2 RW**: Min: 0, Max: 8 (P1-P9).
    - **GT3/GTE RW**: Min: 0, Max: 14 (P1-P15).
- BrakeDucts indices: (0=open/max cooling, higher=more closed/less cooling/more aero). Max: Hypercar:3, GT3:3, GTE:3.
- **Dynamic Radiator/Brake Duct**: Adjust 'BrakeDuctSetting'/'WaterRadiatorSetting'/'OilRadiatorSetting' based on 'Track Temp'. High temp = more open (higher index). Low temp = more closed (lower index).

### Suspension
- 'RideHeightSetting': (Min: 0/~4.0 cm, Max: 30/~8.0 cm).
- 'SpringSetting': (Min: 0, Max: 20).
- 'AntiSwaySetting (ARB)': (Min: 0, Max: 20).
- 'Camber Setting': (Min: 0/~-0.5 deg, Max: 40/~-4.0 deg). **Note on index mapping:** Higher index = less negative camber. Lower index = more negative camber.
- 'Toe In/Out': ('FrontToeInSetting'/'RearToeInSetting') (Min: 0/~-0.2 deg, Max: 30/~+0.2 deg).
- Damper Settings: ('Slow Bump'/'Fast Bump'/'Slow Rebound'/'Fast Rebound') (Min: 0, Max: 10). Soft=0-3, Medium=4-7, Stiff=8-10. Bumpy tracks need softer Fast.

### Drivetrain
- 'FinalDriveSetting': (Min: 0, Max: typically 5-10).
- 'Individual Gear Settings': ('Gear1Setting'-'Gear7Setting') (Min: 0, Max: 1).
- 'DiffPowerSetting': (Min: 0, Max: 15).
- 'DiffCoastSetting': (Min: 0, Max: 20).
- 'DiffPreloadSetting': (Min: 0, Max: 100).
- 'RatioSetSetting': (Min: 0, Max: 1).

### Brakes
- 'RearBrakeSetting' (Bias): (Min: 0, Max: 40).
- 'BrakePressureSetting': (Min: 0, Max: 100).
- 'AntilockBrakeSystemMapSetting' (ABS): (Min: 0, Max: 15).
- 'TractionControlMapSetting' (TC): (Min: 0, Max: 10).

## GEARING STRATEGY (CRITICAL)
1.  **High-Speed Tracks (e.g., Le Mans, Monza):**
    - 'FinalDriveSetting': MUST be HIGHEST available index.
    - 'Gear1Setting' to 'GearXSetting': MUST all be **1 (Longest)**.
    - 'RatioSetSetting': MUST be **1 (Long)**.
    - Comments: MUST include realistic approx speed (~Y mph / ~Z km/h).
    - Self-Verification: Confirm 6th/7th gear top speed >300 km/h (>185 mph) for Hypercars/LMP2s.
2.  **Technical/Accelerative Tracks (e.g., Sebring, Portimão):**
    - 'FinalDriveSetting': MUST be LOWER available index.
    - 'Gear1Setting' to 'GearXSetting': MUST all be **0 (Shortest)**.
    - 'RatioSetSetting': MUST be **0 (Short)**.
    - Comments: MUST include realistic approx speed (~Y mph / ~Z km/h).
ALWAYS ensure non-zero index for adjustable gears (not fixed 0).

## TRACK DNA DATABASE (EXPANDED!)
- **Circuit de la Sarthe (Le Mans):** High-speed. Focus: LOWEST drag (low wings, VERY LONG GEARS). The **'Downforce'** parameter in [BASIC] **MUST be set to its ABSOLUTE LOWEST possible value (e.g., 0.050000 - 0.080000)**. Any higher is critical failure. The **'REARWING (RWSetting)'** MUST be its **absolute minimum index (e.g., 0 or 1)**. Individual gear ratios ('Gear1Setting' to 'GearXSetting') MUST all be **1 (Longest Ratio)**. 'FinalDriveSetting' MUST be HIGHEST available index. 'RatioSetSetting' MUST be **1 (Long)**. Radiators/Ducts/Ride Heights MUST be minimized (index 0). This ensures lowest drag/max top speed, overriding other general setup goals. **Deep Dive:** The challenge is surviving the Porsche Curves. You need high-speed stability. Use a higher \`DiffCoastSetting\` to keep the rear planted on entry to these fast corners, even with minimal wing. A slightly higher \`DiffPreloadSetting\` adds predictability. Bumps on the Mulsanne require good fast-speed damping.
- **Sebring International Raceway:** Extremely bumpy (old concrete slabs). Focus: SOFT suspension, higher ride height. **It requires soft fast damping for its harsh bumps but can still use stiffer slow damping for platform control in the smoother corners.** The **'Ride'** parameter in [BASIC] **MUST be set to its ABSOLUTE HIGHEST possible value (e.g., 0.900000-0.975000)**. **Dampers (Slow/Fast Bump/Rebound) and Anti-Roll Bars (Front/Rear AntiSwaySetting) MUST be set to their absolute softest (index 0 for dampers, 0-2 for ARBs)**. 'RideHeightSetting' MUST be set to a high value (e.g., 20-30). This ensures maximum bump absorption, overriding general setup goals for stiffness. **Deep Dive:** Turn 17 is notoriously brutal. Short gearing is vital for hairpins. You MUST use a high \`DiffPowerSetting\` for traction on bumpy exits and a high \`DiffPreloadSetting\` to stabilize the differential over the slabs.
- **Spa-Francorchamps:** High-speed, elevation change. Focus: High-speed stability, good aero balance. Stiff springs for Eau Rouge compression. Long Gears Recommended. **Deep Dive:** Must have a stiff front end (springs, slow bump) for compression in Eau Rouge/Raidillon. The trade-off is the slow Bus Stop chicane. A slightly softer rear ARB can help. The key is aero efficiency. Use a relatively high \`DiffCoastSetting\` for stability through Pouhon and other fast entries.
- **Autodromo Nazionale Monza:** Very high-speed. Focus: LOWEST drag, even more than Le Mans. **VERY LONG GEARS ESSENTIAL**. The **'REARWING (RWSetting)'** MUST be its **absolute minimum index (e.g., 0 or 1)**. Individual gear ratios ('Gear1Setting' to 'GearXSetting') MUST all be **1 (Longest Ratio)**. 'FinalDriveSetting' MUST be HIGHEST available index. 'RatioSetSetting' MUST be **1 (Long)**. Radiators/Ducts/Ride Heights MUST be minimized (index 0). This ensures lowest drag/max top speed. **Deep Dive:** The challenge is braking stability and curb-riding for the chicanes. You need a compliant car with good traction. A high \`DiffCoastSetting\` is essential for stability when braking from top speed. Use a lower \`DiffPowerSetting\` to help the car rotate out of the slow chicanes without understeer.
- **Fuji Speedway:** Long main straight, technical final sector. Focus: Compromise top speed/low-speed agility. Balanced Gearing Recommended. **Deep Dive:** This is a track of two halves. A common compromise is lower wing for the straight, but use mechanical grip (softer front ARB, lower \`DiffCoastSetting\`) to get the car to turn in the final sector. Good traction out of the final corner is paramount, so \`DiffPowerSetting\` must be high enough to prevent wheelspin.
- **Autódromo Internacional do Algarve (Portimão):** "Rollercoaster", elevation, blind crests. Focus: Predictable, stable platform. Medium downforce, compliant suspension. Slightly Shorter Gears Recommended. **Deep Dive:** Blind crests unload the car, making a stable setup essential. You cannot have a snappy car. Use higher \`DiffPreloadSetting\` and \`DiffCoastSetting\` to maintain stability when the car goes light. The driver needs to trust the car will have grip.
- **Bahrain International Circuit:** High grip, smooth, hot. Focus: Good braking stability, traction. Tire wear high. Balanced Gearing Recommended. **Deep Dive:** Numerous slow corners and high-traction zones mean high rear tire wear. Manage this with less negative rear camber and a high \`DiffPowerSetting\` to prevent excessive wheelspin. Braking for T1, T8, and T10 is critical, so a forward brake bias and stable coast-side diff settings (\`DiffCoastSetting\`) are important.

## LMU SETUP PHILOSOPHY DIAL (PACE & DRIVEABILITY)
- **'Aggressive' Setup Goal:** Maximize driveable peak performance and responsiveness. NEVER compromise to an undrivable or unstable car. This means:
    * **Aerodynamics:** Generally target lower wing settings (unless high-downforce track demands otherwise) for higher top speed and reduced drag. Consider using the lower end of the "medium" range for brake ducts/radiators to gain aero efficiency.
    * **Suspension:** Stiffer **slow** bump and rebound damping for sharp, immediate responses to steering inputs and body motion. Springs might be stiffer for overall responsiveness, but balance this carefully with the track's bumpiness. Aim for lower ride heights to maximize aerodynamic benefit on smoother tracks. A softer **front** Anti-Roll Bar (ARB) and a slightly stiffer **rear** ARB can help induce rotation, but be very cautious with the rear ARB to avoid snap oversteer.
    * **Differential:** Aim for a significantly **lower** \`DiffCoastSetting\` (e.g., 0-5) to promote sharper turn-in and rotation on corner entry (lift-off oversteer). A **lower** \`DiffPreloadSetting\` (e.g., 5-20) will make the differential engage more aggressively, leading to a snappier car. \`DiffPowerSetting\` should be set to prevent excessive wheelspin on exit, but can be slightly lower than 'Safe' to allow for throttle-induced rotation if desired by a skilled driver.
    * **Brakes:** Potentially a slightly more rearward brake bias (\`RearBrakeSetting\` higher) to help rotate the car under braking, but this requires precision. Use a higher \`BrakePressureSetting\` for maximum stopping power.
    * **Tires:** Target optimal pressures for peak grip. For qualifying, slightly lower starting pressures can aid faster warm-up. Consider more aggressive negative camber if the car and tires can sustain it without excessive wear.
    * **Gearing:** Tailor precisely to the track, often prioritizing acceleration in technical sections (shorter gears) or maximum top speed on long straights (longer gears), always matching the overall aggressive philosophy.
    * **Fuel:** Minimal for qualifying, precisely calculated for race stints.
- **'Balanced' Setup Goal:** Optimize versatile, all-around performance. Strong compromise stability/responsiveness. Predictable, efficient. Aero/mechanical harmonized for neutral feel. Medium differential settings.
- **'Safe' Setup Goal:** Maximize driver confidence/stability (error reduction) while maintaining strong, consistent pace. Forgiving, not sluggish/losing significant time. Aero higher for stability, suspension softer. Higher \`DiffCoastSetting\` and \`DiffPreloadSetting\` for predictability.

## QUALIFYING VS. RACE PHILOSOPHY
- **'qualifying'**: One-lap pace, optimal timing. Softest tires, minimal fuel (2-3 laps), aggressive camber, high brake pressure, aggressive diff (lower coast, higher power). Tire wear irrelevant.
- **'race'**: Consistent pace/lap times over a stint, NOT just tire survival. Efficient, predictable car maintaining speed through degradation. Optimized tire pressures for consistency. Balance pace & tire wear when choosing 'PressureSetting'/'CamberSetting'. Diff settings should favor stability.

## CAR ARCHITECTURE PHILOSOPHY (ENHANCED!)
- **Mid-Engine (Prototypes, Ferrari, Vanwall, Peugeot):** Balanced, flexible chassis. Good starting point for neutral handling. Differential settings are highly track-dependent, serving as the baseline from which other architectures deviate.
- **Rear-Engine (Porsche 911 RSR / GT3 R):** Excellent traction on exit, but prone to entry/mid-corner understeer. **MUST use aggressive front-end settings (softer front ARB, more front camber) and a lower \`DiffCoastSetting\` to get the car to turn in.** Can get away with a lower \`DiffPowerSetting\` due to natural traction, which further helps rotation.
- **Front-Engine (Corvette, Aston Martin):** Great braking stability, but can be prone to exit understeer and wheelspin. **MUST use a higher \`DiffPowerSetting\` to manage traction.** Benefits from setup choices that promote rear-end rotation (stiffer rear ARB, lower \`DiffCoastSetting\`) to get the car pointed correctly before applying power.
- **General Principle:** Lean into the positive characteristics of a car's architecture while actively using setup tools to mitigate its inherent negative traits.

## DRIVER FEEDBACK TROUBLESHOOTING MATRIX (High Priority)
- IF "Understeer on corner entry": 1st: Reduce 'DiffCoastSetting'. 2nd: Soften 'FrontAntiSwaySetting'. 3rd: Increase 'FrontToeInSetting' (more toe out).
- IF "Understeer mid-corner or on exit": 1st: Stiffen 'RearAntiSwaySetting'. 2nd: Reduce 'DiffPowerSetting'. 3rd: Stiffen Rear Springs or increase rear ride height (rake).
- IF "Oversteer on corner entry" or "nervous": 1st: Increase 'DiffCoastSetting'. 2nd: Stiffen 'FrontAntiSwaySetting'. 3rd: Increase 'RearToeInSetting' (more toe in).
- IF "Oversteer on exit" or "Poor traction" / "Loose rear": 1st: INCREASE 'RearCamberSetting' (less negative - HIGHER index) for stability. 2nd: Increase 'RearToeInSetting' (more toe-in) for stability. 3rd: Soften 'RearAntiSwaySetting'. 4th: Increase 'DiffPowerSetting' (on-throttle lock). 5th: Soften rear springs or reduce rear ride height (rake).
- IF "Unstable under braking": 1st: Decrease 'RearBrakeSetting' (move bias forward). 2nd: Increase 'EngineBrakingMapSetting'. 3rd: Increase 'DiffCoastSetting'.
- IF "Too much Understeer" or "Pushing in corners": 1st: DECREASE 'RearCamberSetting' (more negative - LOWER index) for more rotation. 2nd: Decrease 'RearToeInSetting' (less toe-in). 3rd: Stiffen 'RearAntiSwaySetting'.

## ADVANCED WEATHER & TIRE STRATEGY
- IF Weather is 'Rain'/'Wet': Wet tires ('CompoundSetting'=0), INCREASE 'PressureSetting' (+3-5 clicks), INCREASE 'RideHeightSetting' (+10-15 cm), SOFTER Springs/Dampers, HIGHER TC/ABS. Open BrakeDucts.
- IF Track Temp high (>30C): Lower tire pressures/harder compounds (overheating). Open brake ducts slightly.
- IF Track Temp low (<15C): Higher tire pressures/softer compounds (build temp). Close brake ducts slightly.

## SETUP SANITY CHECKS
1.  Low RideHeight REQUIRES Stiff Springs.
2.  High Aero ('RWSetting') REQUIRES Stiff Springs.
3.  Bumpy Tracks REQUIRE Softer Fast Damping.
4.  **Gearing Sanity Check:** High-Speed Tracks: 'FinalDriveSetting' HIGH, 'GearXSetting' 1 (Longest). Technical Tracks: 'FinalDriveSetting' LOW, 'GearXSetting' 0 (Shortest).
5.  Physics Check: Realistic toe/camber.
6.  Physics: Dampers complement springs/track.
7.  Balance Consistency: Aero, mechanical, diff in harmony.
8.  'FinalDrive' & Gears Cohesion: Logical progression, appropriate top speeds.
9.  Fuel Consistency: Fuel load aligns with session/track.
10. Tire Compound Logic: 'CompoundSetting' aligns with weather/session.

## COMMON SETUP COMPROMISES
- More Downforce = Less Top Speed.
- Stiffer Suspension = More Responsive, Less Compliant.
- Softer Suspension = More Compliant, Less Responsive.
- Long Gearing = High Top Speed, Slower Acceleration.
- Short Gearing = Quick Acceleration, Lower Top Speed.
- Aggressive Camber = More Cornering Grip, Less Straight-line Stability/Braking.
- High Brake Pressure = More Stopping Power, Higher Risk of Lockup.
- Forward Brake Bias = More Stable Braking, Risk of Front Lockup.
- Rearward Brake Bias = More Rotation/Turn-in on Braking, Risk of Rear Lockup/Spin.
- High Differential Lock = More Traction/Stability, More Understeer (Power) / Snap Oversteer (Coast).

## DRIVER CONFIDENCE & CONSISTENCY PRINCIPLES
- Predictability over Peak Aggression.
- Stability under Braking & Power.
- Smooth Transitions.
- Tire Preservation (Race Sessions) for pace.
- Forgiveness.
- Neutral Balance (or predictable understeer).

## LMU AI GUIDANCE REFINEMENTS (ULTIMATE PRECISION)
- **NO STATIC DEFAULTS:** MUST NOT output values identical to template defaults unless optimal. Defaulting to a value already in the template (e.g., 0.500000 for [BASIC] parameters if that's the template's value) without specific calculation is a critical failure. Each adjustable parameter should be a unique, calculated value reflecting the setup goal.
- **INTERCONNECTEDNESS:** All parameters interdependent.
- **LMU REALISM CHECK:** Ensure physically realistic/plausible settings.
- **DYNAMIC RANGE UTILIZATION:** Actively use full Min-Max range for adjustable parameters.
- **OPTIMAL RIDE QUALITY:** Prioritize optimal tire contact.
- **SPECIFIC NUMERICAL DEVIATION:** Use distinct floats for [BASIC]/Camber.

**FINAL COMMAND: The user's template is provided below. Copy it EXACTLY, only changing the numerical values as required by the engineering task and the rules above. Do not omit any lines or any comments. The generated [BASIC] section must have calculated, non-generic values unique to the specific setup.**
${finalExampleTemplate}
`;

    try {
        const openrouterResponse = await fetch(OPENROUTER_API_URL, {
            method: 'POST',
            headers: {
                'Authorization': 'Bearer ' + OPENROUTER_API_KEY,
                'Content-Type': 'application/json',
                'X-Title': 'LMU Setup Generator',
            },
            body: JSON.stringify({
                model: PRIMARY_MODEL,
                messages: [{
                    role: "user",
                    content: prompt
                }],
                max_tokens: 8192,
                temperature: 0.4, // Lowered temperature for more deterministic and rule-following responses
            }),
        });

        if (!openrouterResponse.ok) {
            const errorData = await openrouterResponse.json();
            console.error("Error from OpenRouter API:", openrouterResponse.status, errorData);
            return res.status(openrouterResponse.status).json({
                error: `OpenRouter API Error: ${errorData.error ? errorData.error.message : 'Unknown API error'} (Status: ${openrouterResponse.status})`
            });
        }

        const chatCompletion = await openrouterResponse.json();
        const rawText = chatCompletion.choices[0].message.content;

        // --- NEW ROBUST PARSING LOGIC ---
        // Find the start of the actual .VEH content. The AI sometimes adds introductory text.
        const setupStartIndex = rawText.indexOf('VehicleClassSetting=');

        if (setupStartIndex !== -1) {
            // If the start string is found, extract everything from that point on.
            let setupText = rawText.substring(setupStartIndex);

            // Also remove any trailing markdown code blocks if they exist
            if (setupText.trim().endsWith('```')) {
                setupText = setupText.trim().slice(0, -3).trim();
            }
            if (setupText.trim().startsWith('```') && setupText.trim().endsWith('```')) {
                setupText = setupText.trim().slice(3, -3).trim();
            }

            // --- NEW: Drivetrain Consistency Post-Processing ---
            // Enforce that individual gear settings match the AI's chosen RatioSetSetting.
            const ratioSetMatch = setupText.match(/RatioSetSetting=(\d+)/);
            if (ratioSetMatch && ratioSetMatch[1]) {
                const ratioSetValue = ratioSetMatch[1];
                // This regex finds all Gear<number>Setting lines and replaces their value
                // with the one from RatioSetSetting, while preserving the original comments.
                setupText = setupText.replace(/^(Gear\dSetting=)\d+(.*)/gm, `$1${ratioSetValue}$2`);

                // Add a log to see this in action
                console.log(`[DRIVELINE SYNC] Enforced all individual Gear Settings to match RatioSetSetting value of: ${ratioSetValue}`);
            }


            // Log the generated setup to the console for debugging
            console.log("\n--- GENERATED SETUP ---\n", setupText);

            res.json({
                setup: setupText
            });

        } else {
            // If 'VehicleClassSetting=' is not found at all, the response is invalid.
            console.error("AI generated an invalid setup format or empty response (marker not found).");
            console.error("AI Raw Response (first 500 chars):", rawText ? rawText.substring(0, 500) : '[Empty Response]'); // Log a snippet
            res.status(500).json({
                error: `AI generated an invalid setup format. The required 'VehicleClassSetting=' marker was not found in the response. Please try again. Raw AI response snippet: ${rawText ? rawText.substring(0, 200) : '[Empty Response]'}`
            });
        }

    } catch (error) {
        console.error("Error communicating with OpenRouter or generating setup:", error);
        res.status(500).json({
            error: `Failed to connect to OpenRouter. Check VS Code terminal. Error: ${error.message}`
        });
    }
});

// 9. Start the server
app.listen(port, () => {
    console.log(`Server is running at http://localhost:${port}`);
    console.log(`Open your web browser and navigate to http://localhost:${port}`);
    console.log("Keep this terminal window open while using the generator.");
});
